import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import type { MoldTypePageData } from "@/lib/mold-type-pages";
import { site } from "@/lib/site";

function Heading({ eyebrow, title, body }: { eyebrow?: string; title: string; body?: string }) {
  return <div className="max-w-4xl">{eyebrow ? <p className="text-xs font-extrabold uppercase tracking-[0.15em] text-[var(--brand)] sm:text-sm">{eyebrow}</p> : null}<h2 className="mt-3 text-3xl font-extrabold leading-[1.1] tracking-[-0.02em] text-[var(--brand-dark)] sm:text-4xl lg:text-5xl">{title}</h2>{body ? <p className="mt-5 max-w-3xl text-base leading-7 text-[var(--muted)] sm:text-lg sm:leading-8">{body}</p> : null}</div>;
}

function ArrowLink({ href, children }: { href: string; children: ReactNode }) {
  return <Link className="focus-ring inline-flex items-center gap-2 rounded-sm font-bold text-[var(--brand)] transition hover:text-[var(--brand-dark)]" href={href}>{children}<span aria-hidden="true">→</span></Link>;
}

export function MoldTypePage({ page }: { page: MoldTypePageData }) {
  const pageUrl = `${site.url}/injection-molds/${page.slug}/`;
  const schemas = [
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: site.url }, { "@type": "ListItem", position: 2, name: "Injection Molds", item: `${site.url}/injection-molds/` }, { "@type": "ListItem", position: 3, name: page.name, item: pageUrl }] },
    { "@context": "https://schema.org", "@type": "WebPage", "@id": `${pageUrl}#webpage`, name: page.h1, description: page.metaDescription, url: pageUrl },
    { "@context": "https://schema.org", "@type": "Service", name: page.name, serviceType: `${page.name} engineering and tooling`, description: page.metaDescription, url: pageUrl, mainEntityOfPage: { "@id": `${pageUrl}#webpage` }, provider: { "@type": "Organization", name: site.name, url: site.url }, areaServed: "Worldwide" },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: page.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }
  ];

  return <>
    {schemas.map((schema, index) => <script dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} key={index} type="application/ld+json" />)}

    <nav aria-label="Breadcrumb" className="border-b border-[var(--line)] bg-white"><ol className="container-page flex flex-wrap items-center gap-2 py-4 text-sm text-[var(--muted)]"><li><Link className="focus-ring rounded-sm hover:text-[var(--brand)]" href="/">Home</Link></li><li aria-hidden="true">/</li><li><Link className="focus-ring rounded-sm hover:text-[var(--brand)]" href="/injection-molds">Injection Molds</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="font-semibold text-[var(--brand-dark)]">{page.name}</li></ol></nav>

    <section className="border-b border-[var(--line)] bg-[var(--surface-soft)]"><div className="container-page grid items-center gap-9 py-12 lg:grid-cols-[minmax(0,40fr)_minmax(0,60fr)] lg:gap-12 lg:py-16"><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-[var(--brand)] sm:text-sm">Injection Mold Type</p><h1 className="split-hero-title mt-4 text-[var(--brand-dark)]">{page.h1}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[var(--muted)] sm:text-lg sm:leading-8">{page.heroBody}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link className="focus-ring inline-flex min-h-12 items-center justify-center rounded-sm bg-[var(--brand)] px-6 py-3 text-center font-bold text-white hover:bg-[var(--brand-hover)]" href="/request-a-quote">Upload CAD for DFM Review</Link><Link className="focus-ring inline-flex min-h-12 items-center justify-center rounded-sm border border-[var(--brand-dark)] px-6 py-3 text-center font-bold text-[var(--brand-dark)] hover:border-[var(--brand)] hover:text-[var(--brand)]" href="/request-a-quote">Request Tooling Quote</Link></div></div><div className="relative aspect-[4/3] overflow-hidden rounded-sm border border-[var(--line)] bg-white"><Image alt={page.heroAlt} className="object-cover object-center" fill priority sizes="(min-width: 1024px) 60vw, 100vw" src={page.heroImage} /></div></div></section>

    <section className="bg-white py-14 sm:py-16"><div className="container-page grid gap-10 lg:grid-cols-[minmax(0,58fr)_minmax(0,42fr)] lg:items-start"><Heading eyebrow="What Makes This Tooling Different" title={`What Defines ${page.name}`} body={page.difference} /><div className="border-l-4 border-[var(--brand)] bg-[var(--surface-soft)] p-6"><h3 className="text-xl font-bold text-[var(--brand-dark)]">Project Selection Check</h3><p className="mt-3 leading-7 text-[var(--muted)]">This tooling route should be selected from the part, material, production demand and receiving-machine requirements—not from a category name alone.</p><div className="mt-5"><ArrowLink href="/injection-molding-engineering">Start with DFM Engineering</ArrowLink></div></div></div></section>

    <section className="bg-[var(--surface-soft)] py-14 sm:py-16"><div className="container-page"><Heading eyebrow="Selection Criteria" title="When This Tooling Is Used" /><ol className="mt-8 grid gap-x-10 gap-y-7 md:grid-cols-3">{page.criteria.map((item, index) => <li className="grid grid-cols-[auto_1fr] gap-4 border-t border-[var(--line)] pt-5" key={item}><span className="text-sm font-extrabold text-[var(--brand)]">{String(index + 1).padStart(2, "0")}</span><p className="font-semibold leading-7 text-[var(--brand-dark)]">{item}</p></li>)}</ol></div></section>

    <section className="bg-white py-14 sm:py-16"><div className="container-page"><Heading eyebrow="Type-Specific Engineering" title={`Engineering Priorities for ${page.name}`} /><div className="mt-9 grid gap-x-8 gap-y-8 md:grid-cols-2 lg:grid-cols-4">{page.engineering.map((item) => <article className="border-t-2 border-[var(--brand)] pt-5" key={item.title}><h3 className="text-xl font-bold text-[var(--brand-dark)]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)] sm:text-base sm:leading-7">{item.body}</p></article>)}</div></div></section>

    <section className="bg-[var(--brand-dark)] py-14 text-white sm:py-16"><div className="container-page grid gap-10 lg:grid-cols-[minmax(0,42fr)_minmax(0,58fr)] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-red-200 sm:text-sm">Critical Tooling Topic</p><h2 className="mt-3 text-3xl font-extrabold leading-[1.1] tracking-[-0.02em] sm:text-4xl">{page.critical.title}</h2><p className="mt-5 text-base leading-7 text-white/75 sm:text-lg">{page.critical.body}</p></div><ol className="grid gap-3 sm:grid-cols-2">{page.critical.points.map((point, index) => <li className="border-l border-white/30 bg-white/[0.04] p-5" key={point}><span className="text-xs font-extrabold text-red-200">{String(index + 1).padStart(2, "0")}</span><p className="mt-2 font-bold leading-6">{point}</p></li>)}</ol></div></section>

    <section className="bg-white py-14 sm:py-16"><div className="container-page grid gap-10 lg:grid-cols-[minmax(0,48fr)_minmax(0,52fr)] lg:items-center"><div className="relative aspect-[16/10] overflow-hidden rounded-sm border border-[var(--line)] bg-[var(--surface-soft)]"><Image alt={page.supportAlt} className="object-cover object-center" fill sizes="(min-width: 1024px) 48vw, 100vw" src={page.supportImage} /></div><div><Heading eyebrow="Real Engineering Evidence" title="Tooling Evidence & Project Context" body={page.evidence} />{page.needsAssetReplacement ? <p className="mt-5 border-l-4 border-amber-500 pl-4 text-sm leading-6 text-[var(--muted)]">The current visual is intentionally described by what it actually shows; it is not presented as a verified page-specific project.</p> : null}</div></div></section>

    <section className="bg-[var(--surface-soft)] py-14 sm:py-16"><div className="container-page"><Heading eyebrow="Trial & Validation" title={`${page.name} Validation Priorities`} /><ol className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{page.validation.map((item, index) => <li className="bg-white p-5" key={item.title}><span className="text-sm font-extrabold text-[var(--brand)]">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-3 text-lg font-bold text-[var(--brand-dark)]">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.body}</p></li>)}</ol><div className="mt-7"><ArrowLink href="/injection-molds/mold-trial-validation">View Mold Trial & Validation</ArrowLink></div></div></section>

    <section className="bg-white py-14 sm:py-16"><div className="container-page grid gap-12 lg:grid-cols-2"><div><Heading eyebrow="Related Capabilities" title="Continue Your Tooling Review" /><div className="mt-7 grid gap-3">{page.related.map((item) => <Link className="focus-ring group flex items-center justify-between border-b border-[var(--line)] py-4 font-bold text-[var(--brand-dark)] hover:border-[var(--brand)] hover:text-[var(--brand)]" href={item.href} key={item.href}>{item.label}<span className="transition group-hover:translate-x-1" aria-hidden="true">→</span></Link>)}</div></div><div><Heading eyebrow="Project Inputs" title="Information for Engineering Review" /><ul className="mt-7 grid gap-3 text-[var(--muted)]"><li className="border-l-2 border-[var(--brand)] pl-4">3D CAD and controlled 2D drawings</li><li className="border-l-2 border-[var(--brand)] pl-4">Resin, finish and functional requirements</li><li className="border-l-2 border-[var(--brand)] pl-4">Expected volume and receiving-machine information</li><li className="border-l-2 border-[var(--brand)] pl-4">Critical dimensions and approval expectations</li></ul></div></div></section>

    <section className="bg-[var(--surface-soft)] py-14 sm:py-16"><div className="container-page max-w-5xl"><Heading eyebrow="FAQ" title={`${page.name} FAQ`} /><div className="mt-8 divide-y divide-[var(--line)] border-y border-[var(--line)]">{page.faqs.map((faq) => <details className="group py-5" key={faq.question}><summary className="focus-ring cursor-pointer rounded-sm pr-8 text-lg font-bold text-[var(--brand-dark)] marker:text-[var(--brand)]">{faq.question}</summary><p className="mt-4 max-w-4xl leading-7 text-[var(--muted)]">{faq.answer}</p></details>)}</div></div></section>

    <section className="border-t border-[var(--cta-border)] bg-[var(--cta-bg)] py-14 sm:py-16"><div className="container-page grid gap-8 lg:grid-cols-[minmax(0,58fr)_minmax(320px,42fr)] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--brand)]">Start Your Tooling Review</p><h2 className="mt-3 text-3xl font-bold leading-tight text-[var(--cta-heading)] sm:text-4xl">Discuss Your {page.name} Project</h2><p className="mt-4 max-w-3xl leading-7 text-[var(--cta-body)]">Send your CAD data, material, volume and receiving-machine requirements for DFM review and tooling quotation.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link className="focus-ring inline-flex min-h-14 items-center justify-center rounded-sm bg-[var(--brand)] px-6 font-bold text-white hover:bg-[var(--brand-hover)]" href="/request-a-quote">Upload CAD for DFM Review</Link><Link className="focus-ring inline-flex min-h-14 items-center justify-center rounded-sm border border-[var(--cta-heading)] bg-white px-6 font-bold text-[var(--cta-heading)] hover:bg-[var(--cta-heading)] hover:text-white" href="/request-a-quote">Request Tooling Quote</Link></div></div></section>
  </>;
}
