import Image from "next/image";
import Link from "next/link";
import { FullBleedHero } from "@/components/FullBleedHero";
import { toolingSupportPages, type ToolingSupportSlug } from "@/lib/tooling-support-pages";
import { site } from "@/lib/site";

const supportLinks = [
  { slug: "mold-trial-validation", label: "Mold Trial & Validation", body: "Review trials, samples, molding parameters and validation status." },
  { slug: "tooling-documentation", label: "Tooling Documentation", body: "Prepare drawings, records and project-specific handover information." },
  { slug: "mold-spare-parts", label: "Mold Spare Parts", body: "Plan replacement inserts and identified tooling components." },
  { slug: "export-tooling-transfer", label: "Export Tooling & Mold Transfer", body: "Prepare the tool and agreed handover package for customer production." }
] as const;

function Heading({ eyebrow, title, intro, id }: { eyebrow: string; title: string; intro?: string; id: string }) {
  return <div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--brand)]">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold leading-tight text-[var(--brand-dark)] sm:text-4xl lg:text-[2.75rem]" id={id}>{title}</h2>{intro ? <p className="mt-4 max-w-3xl text-base leading-7 text-[var(--muted)] sm:text-lg sm:leading-8">{intro}</p> : null}</div>;
}

function AccentList({ items }: { items: string[] }) {
  return <ul className="grid gap-3">{items.map((item) => <li className="border-l-2 border-[var(--brand)] pl-4 font-semibold leading-6 text-[var(--brand-dark)]" key={item}>{item}</li>)}</ul>;
}

function EvidenceImage({ src, alt, title, body, className = "aspect-[16/10]" }: { src: string; alt: string; title: string; body?: string; className?: string }) {
  return <figure className="overflow-hidden rounded-md border border-[var(--line)] bg-white"><div className={`relative bg-[var(--surface-soft)] ${className}`}><Image alt={alt} className="object-contain" fill sizes="(min-width: 1024px) 46vw, 100vw" src={src} /></div><figcaption className="border-t border-[var(--line)] p-4"><p className="font-bold text-[var(--brand-dark)]">{title}</p>{body ? <p className="mt-1 text-sm leading-6 text-[var(--muted)]">{body}</p> : null}</figcaption></figure>;
}

function Workflow({ steps }: { steps: string[] }) {
  return <ol className="grid gap-0 md:grid-cols-3 lg:grid-cols-7">{steps.map((step, index) => <li className="relative border-l border-[var(--line)] py-4 pl-5 md:border-l-0 md:border-t md:px-3 md:pt-6" key={step}><span className="absolute -left-[5px] top-5 h-2.5 w-2.5 rounded-full bg-[var(--brand)] md:-top-[5px] md:left-3" /><span className="text-xs font-bold uppercase tracking-[0.1em] text-[var(--brand)]">{String(index + 1).padStart(2, "0")}</span><p className="mt-1 text-sm font-bold leading-5 text-[var(--brand-dark)]">{step}</p></li>)}</ol>;
}

function TrialPage() {
  const validation = [
    ["Filling & Part Formation", "Check whether the part fills as intended and review visible molding issues."],
    ["Gate & Runner Performance", "Review gating behavior, runner performance and gate-related appearance."],
    ["Part Release & Ejection", "Check mold opening, part release and ejection behavior."],
    ["Appearance & Surface", "Review visible surfaces, parting lines, gate marks, texture and other appearance requirements."],
    ["Critical Dimensions", "Verify agreed critical dimensions through dimensional inspection where required."],
    ["Process Stability", "Record and review relevant molding conditions for repeatable trial results."]
  ];
  return <>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="trial-validation-scope"><div className="container-page"><Heading eyebrow="Validation Scope" id="trial-validation-scope" title="What We Validate During Mold Trials" intro="Mold function, molded-part condition and recorded process information are reviewed together before the tooling moves to its next agreed step." /><div className="mt-8 grid gap-x-10 gap-y-0 border-y border-[var(--line)] md:grid-cols-2 lg:grid-cols-3">{validation.map(([title, body], index) => <article className="border-b border-[var(--line)] py-5 lg:[&:nth-last-child(-n+3)]:border-b-0" key={title}><p className="text-xs font-bold text-[var(--brand)]">0{index + 1}</p><h3 className="mt-2 text-lg font-bold text-[var(--brand-dark)]">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{body}</p></article>)}</div></div></section>
    <section className="bg-[var(--surface-soft)] py-14 sm:py-16" aria-labelledby="trial-workflow"><div className="container-page"><Heading eyebrow="Trial Workflow" id="trial-workflow" title="From T0 Trial to Validation" intro="Trial stages and correction loops remain project-specific; correction or re-trial is completed when required." /><div className="mt-10"><Workflow steps={["Mold Assembly", "T0 Trial", "Sample Review", "Dimensional Inspection", "Engineering Review", "Correction / Re-Trial When Required", "Approval / Next Step"]} /></div></div></section>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="trial-evidence"><div className="container-page"><Heading eyebrow="Documented Evidence" id="trial-evidence" title="What You Receive from Mold Trial & Validation" intro="Available records are aligned with the project requirements and agreed validation scope." /><div className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_0.75fr]"><EvidenceImage alt="Injection mold trial report documenting mold condition and validation" body="Trial setup, mold condition, observations and validation records." className="aspect-[16/11]" src="/images/injection-mold-manufacturing/mold-trial-report-evidence.webp" title="Mold Trial Report" /><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-1"><EvidenceImage alt="Injection molding process parameter sheet from mold trial" src="/images/injection-mold-manufacturing/injection-molding-process-parameters.webp" title="Molding Parameters" /><EvidenceImage alt="Dimensional inspection report for injection molded trial samples" src="/images/quality/dimensional-inspection-report-anonymized.webp" title="Dimensional Inspection" /></div></div><div className="mt-7"><AccentList items={["Trial Samples", "Trial Findings", "Correction / Open Item Status", "Approval / Confirmation Records where applicable"]} /></div></div></section>
    <section className="bg-[var(--surface-soft)] py-14 sm:py-16" aria-labelledby="trial-next-step"><div className="container-page"><Heading eyebrow="Next Production Step" id="trial-next-step" title="From Mold Validation to the Next Production Step" /><div className="mt-8 grid gap-px overflow-hidden rounded-md border border-[var(--line)] bg-[var(--line)] md:grid-cols-2"><article className="bg-white p-6 sm:p-8"><h3 className="text-2xl font-bold text-[var(--brand-dark)]">Export Tooling</h3><p className="mt-3 leading-7 text-[var(--muted)]">Validated tooling can move toward documentation, spare parts preparation, packing and transfer to the customer production site.</p><Link className="focus-ring mt-5 inline-flex font-bold text-[var(--brand)]" href="/injection-molds/export-tooling-transfer">Explore Export Tooling & Mold Transfer →</Link></article><article className="bg-white p-6 sm:p-8"><h3 className="text-2xl font-bold text-[var(--brand-dark)]">Arktech Injection Production</h3><p className="mt-3 leading-7 text-[var(--muted)]">Projects that remain with Arktech can continue from tooling validation into plastic injection molding production.</p><Link className="focus-ring mt-5 inline-flex font-bold text-[var(--brand)]" href="/plastic-injection-molding">Explore Plastic Injection Molding →</Link></article></div></div></section>
  </>;
}

function DocumentationPage() {
  const groups = [
    ["Mold Design Files", ["3D Mold Data", "2D Mold Drawings", "Insert / Component Drawings", "Relevant tooling details"]],
    ["Mold BOM & Component Information", ["Mold BOM", "Standard component references", "Hot runner information where applicable", "Electrical / connection information where applicable"]],
    ["Material & Tooling Records", ["Mold steel information", "Material records", "Heat-treatment information where applicable", "Project-specific tooling specifications"]],
    ["Trial & Validation Records", ["Mold trial information", "Molding parameters", "Dimensional inspection", "Sample / correction / approval status"]]
  ] as const;
  return <>
    <section className="scroll-mt-24 bg-white py-14 sm:py-16" id="documentation-package" aria-labelledby="documentation-package-heading"><div className="container-page"><Heading eyebrow="Project-Specific Package" id="documentation-package-heading" title="What Can Be Included in the Tooling Documentation Package" intro="The exact handover package is defined by project requirements. The following records can be included where applicable." /><div className="mt-8 grid gap-x-10 gap-y-8 border-y border-[var(--line)] py-8 md:grid-cols-2">{groups.map(([title, items]) => <article key={title}><h3 className="text-xl font-bold text-[var(--brand-dark)]">{title}</h3><div className="mt-4"><AccentList items={[...items]} /></div></article>)}</div></div></section>
    <section className="bg-[var(--surface-soft)] py-14 sm:py-16" aria-labelledby="documentation-examples"><div className="container-page"><Heading eyebrow="Real Project Records" id="documentation-examples" title="Examples of Tooling Documentation" intro="These anonymized and project-safe examples show the technical nature of the tooling handover records." /><div className="mt-8 grid gap-5 md:grid-cols-3"><EvidenceImage alt="Anonymized injection mold drawing and DFM tooling documentation" src="/images/Engineering/injection-molding-dfm-report-anonymized.webp" title="Tooling Design Review" /><EvidenceImage alt="Injection molding process parameter sheet used in tooling validation" src="/images/injection-mold-manufacturing/injection-molding-process-parameters.webp" title="Process Parameter Sheet" /><EvidenceImage alt="Anonymized dimensional inspection report for tooling validation" src="/images/quality/dimensional-inspection-report-anonymized.webp" title="Dimensional Report" /></div></div></section>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="documentation-use"><div className="container-page grid gap-10 lg:grid-cols-2"><div><Heading eyebrow="Maintenance Reference" id="documentation-use" title="Documentation for Mold Maintenance & Spare Parts" intro="Project records can help identify inserts, components and replacement-part references after the mold enters production." /><div className="mt-6"><AccentList items={["Insert identification", "Component references", "Replacement-part references", "Maintenance drawings where applicable"]} /></div><Link className="focus-ring mt-6 inline-flex font-bold text-[var(--brand)]" href="/injection-molds/mold-spare-parts">Explore Mold Spare Parts →</Link></div><div className="border-t border-[var(--line)] pt-8 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--brand)]">Technical Transfer</p><h2 className="mt-3 text-3xl font-bold text-[var(--brand-dark)]">Documentation for Export Tooling & Mold Transfer</h2><p className="mt-4 leading-7 text-[var(--muted)]">Project-specific documentation can support customer mold setup, technical handover, machine-side preparation, maintenance reference and spare-part identification.</p><Link className="focus-ring mt-6 inline-flex font-bold text-[var(--brand)]" href="/injection-molds/export-tooling-transfer">Explore Export Tooling & Mold Transfer →</Link></div></div></section>
  </>;
}

function SparePartsPage() {
  return <>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="spare-parts-scope"><div className="container-page"><Heading eyebrow="Replacement Components" id="spare-parts-scope" title="Injection Mold Spare Parts We Can Support" intro="Spare-part scope is defined by the original tool design, identified wear areas and project-specific production requirements." /><div className="mt-8 grid gap-px overflow-hidden rounded-md border border-[var(--line)] bg-[var(--line)] md:grid-cols-3"><article className="bg-white p-6"><h3 className="text-xl font-bold text-[var(--brand-dark)]">Mold Inserts</h3><div className="mt-5"><AccentList items={["Core Inserts", "Cavity Inserts", "Replaceable Forming Inserts", "Project-Specific Inserts"]} /></div></article><article className="bg-white p-6"><h3 className="text-xl font-bold text-[var(--brand-dark)]">Mold Action Components</h3><div className="mt-5"><AccentList items={["Slider Components", "Lifter Components", "Unscrewing Components where applicable", "Other project-specific mold-action components"]} /></div></article><article className="bg-white p-6"><h3 className="text-xl font-bold text-[var(--brand-dark)]">Wear & Replacement Components</h3><div className="mt-5"><AccentList items={["Ejector Components", "Guide Components", "Bushings", "Other identified wear components where applicable"]} /></div></article></div></div></section>
    <section className="bg-[var(--surface-soft)] py-14 sm:py-16" aria-labelledby="spare-planning"><div className="container-page grid items-center gap-10 lg:grid-cols-[0.95fr_1.05fr]"><div><Heading eyebrow="Export Tooling" id="spare-planning" title="Spare Parts Planning for Export Tooling" intro="Export tooling may require project-specific spare components based on mold design, wear areas, production needs and customer requirements." /><div className="mt-6"><AccentList items={["Spare core or cavity inserts where required", "Identified wear components", "Replacement inserts", "Corresponding drawings and identification"]} /></div></div><EvidenceImage alt="Injection mold spare inserts and project-specific replacement components" className="aspect-[4/3]" src="/images/capabilities/tooling-spare-parts.jpg" title="Project-Specific Mold Inserts" /></div></section>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="replacement-workflow"><div className="container-page"><Heading eyebrow="After Mold Delivery" id="replacement-workflow" title="Replacement Support After Mold Delivery" intro="Replacement requirements are reviewed against the original tool and available project records; timing and scope remain project-specific." /><div className="mt-10"><Workflow steps={["Identify Tool / Component", "Confirm Drawing / Reference", "Review Replacement Requirement", "Manufacture Replacement Part", "Inspection", "Shipment / Handover"]} /></div></div></section>
    <section className="bg-[var(--surface-soft)] py-14 sm:py-16"><div className="container-page grid gap-10 md:grid-cols-2"><article><h2 className="text-3xl font-bold text-[var(--brand-dark)]">Documentation for Spare-Part Identification</h2><p className="mt-4 leading-7 text-[var(--muted)]">Replacement support is easier when project-specific drawings, BOM references and insert identification remain linked to the original tooling documentation.</p><Link className="focus-ring mt-5 inline-flex font-bold text-[var(--brand)]" href="/injection-molds/tooling-documentation">Explore Tooling Documentation →</Link></article><article className="border-t border-[var(--line)] pt-8 md:border-l md:border-t-0 md:pl-10 md:pt-0"><h2 className="text-3xl font-bold text-[var(--brand-dark)]">Spare Parts for Tooling Transfer</h2><p className="mt-4 leading-7 text-[var(--muted)]">Spare components can be prepared together with export tooling according to project requirements before mold transfer.</p><Link className="focus-ring mt-5 inline-flex font-bold text-[var(--brand)]" href="/injection-molds/export-tooling-transfer">Explore Export Tooling & Mold Transfer →</Link></article></div></section>
  </>;
}

function ExportToolingPage() {
  const checks = ["Customer Machine Compatibility", "Mold Dimensions & Interfaces", "Ejection Requirements", "Cooling / Water Connections", "Electrical Interfaces where applicable", "Hot Runner Interfaces where applicable", "Customer Tooling Standards"];
  const review = [
    ["Mold Trial", "/injection-molds/mold-trial-validation"], ["Dimensional Validation", "/injection-molds/mold-trial-validation#trial-evidence"], ["Tooling Inspection", "/injection-mold-manufacturing"], ["Documentation", "/injection-molds/tooling-documentation"], ["Spare Parts", "/injection-molds/mold-spare-parts"], ["Packing Preparation", "#packing-preparation"]
  ] as const;
  return <>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="customer-production"><div className="container-page grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><Heading eyebrow="Receiving Environment" id="customer-production" title="Tooling Prepared for Customer Production" intro="Tool interfaces and customer production requirements are reviewed before handover using the available machine and tooling information." /><div className="grid gap-3 sm:grid-cols-2"><AccentList items={checks.slice(0, 4)} /><AccentList items={checks.slice(4)} /></div></div></section>
    <section className="bg-[var(--surface-soft)] py-14 sm:py-16" aria-labelledby="before-export"><div className="container-page"><Heading eyebrow="Release Review" id="before-export" title="What We Review Before Mold Export" intro="The final review connects tooling validation, project records and physical handover preparation." /><div className="mt-8 grid gap-px overflow-hidden rounded-md border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2 lg:grid-cols-3">{review.map(([label, href], index) => <Link className="focus-ring group bg-white p-5 transition hover:bg-[#fff8f8]" href={href} key={label}><span className="text-xs font-bold text-[var(--brand)]">0{index + 1}</span><h3 className="mt-2 text-lg font-bold text-[var(--brand-dark)] group-hover:text-[var(--brand)]">{label}</h3><span className="mt-3 inline-flex text-sm font-bold text-[var(--brand)]">Review details →</span></Link>)}</div></div></section>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="handover-package"><div className="container-page"><Heading eyebrow="Tooling Handover" id="handover-package" title="Export Tooling Handover Package" intro="The package is assembled around the agreed project scope rather than a fixed one-size-fits-all checklist." /><div className="mt-8 grid gap-5 md:grid-cols-3"><EvidenceImage alt="Finished export injection mold and corresponding molded plastic part" src="/images/company/Precision Mold to Global Delivery.png" title="Finished Mold & Trial Evidence" /><EvidenceImage alt="Injection mold tooling documentation package for customer handover" src="/images/documentation/tooling-documentation-package.png" title="Tooling Documentation" /><EvidenceImage alt="Project-specific injection mold spare inserts prepared for handover" src="/images/capabilities/tooling-spare-parts.jpg" title="Spare Parts" /></div></div></section>
    <section className="scroll-mt-24 bg-[var(--surface-soft)] py-14 sm:py-16" id="packing-preparation" aria-labelledby="packing-heading"><div className="container-page grid gap-10 lg:grid-cols-2"><div><Heading eyebrow="Export Preparation" id="packing-heading" title="Mold Packing & Export Preparation" intro="Where required, tooling handover can include mold protection, rust-prevention preparation, tool identification, spare-part packing and the agreed documentation package." /><p className="mt-5 text-sm leading-6 text-[var(--muted)]">Packing requirements remain project-specific and are confirmed before shipment preparation.</p></div><div className="border-t border-[var(--line)] pt-8 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><h2 className="text-3xl font-bold text-[var(--brand-dark)]">Technical Handover for Customer Production</h2><p className="mt-4 leading-7 text-[var(--muted)]">Technical handover can include project-specific tooling information, trial records, component references and engineering clarification to help the customer prepare the mold for production.</p><div className="mt-5"><AccentList items={["Mold documentation", "Trial information", "Spare-parts references", "Tooling setup information where applicable", "Technical clarification"]} /></div></div></div></section>
    <section className="bg-white py-14 sm:py-16" aria-labelledby="after-transfer"><div className="container-page"><Heading eyebrow="After Handover" id="after-transfer" title="Support After Mold Transfer" intro="After transfer, support can include technical clarification, tooling records, replacement inserts or spare parts, and project-specific modification review where applicable." /><div className="mt-7 flex flex-wrap gap-4"><Link className="focus-ring inline-flex min-h-11 items-center rounded-sm border border-[var(--line)] px-5 font-bold text-[var(--brand-dark)] hover:border-[var(--brand)] hover:text-[var(--brand)]" href="/injection-molds/tooling-documentation">View Tooling Documentation →</Link><Link className="focus-ring inline-flex min-h-11 items-center rounded-sm border border-[var(--line)] px-5 font-bold text-[var(--brand-dark)] hover:border-[var(--brand)] hover:text-[var(--brand)]" href="/injection-molds/mold-spare-parts">View Mold Spare Parts →</Link></div></div></section>
  </>;
}

function FaqSection({ slug }: { slug: ToolingSupportSlug }) {
  const page = toolingSupportPages[slug];
  return <section className="bg-[var(--surface-soft)] py-14 sm:py-16" aria-labelledby="tooling-support-faq"><div className="container-page"><Heading eyebrow="FAQ" id="tooling-support-faq" title={`${page.navLabel} FAQ`} /><div className="mt-8 divide-y divide-[var(--line)] border-y border-[var(--line)]">{page.faqs.map((faq) => <details className="group py-5" key={faq.question}><summary className="focus-ring flex cursor-pointer list-none items-center justify-between gap-5 font-bold text-[var(--brand-dark)]"><span>{faq.question}</span><span aria-hidden="true" className="text-[var(--brand)] transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-4xl pr-8 leading-7 text-[var(--muted)]">{faq.answer}</p></details>)}</div></div></section>;
}

function RelatedSupport({ current }: { current: ToolingSupportSlug }) {
  return <section className="bg-white py-12" aria-labelledby="related-tooling-support"><div className="container-page"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--brand)]">Tooling Support</p><h2 className="mt-3 text-2xl font-bold text-[var(--brand-dark)]" id="related-tooling-support">Related tooling support</h2><div className="mt-6 grid gap-px overflow-hidden rounded-md border border-[var(--line)] bg-[var(--line)] md:grid-cols-3">{supportLinks.filter((item) => item.slug !== current).map((item) => <Link className="focus-ring group bg-white p-5 transition hover:bg-[#fff8f8]" href={`/injection-molds/${item.slug}`} key={item.slug}><h3 className="font-bold text-[var(--brand-dark)] group-hover:text-[var(--brand)]">{item.label}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.body}</p><span className="mt-4 inline-flex text-sm font-bold text-[var(--brand)]">Explore →</span></Link>)}</div></div></section>;
}

function FinalCta({ slug }: { slug: ToolingSupportSlug }) {
  const exportPage = slug === "export-tooling-transfer";
  return <section className="bg-[#102A43] py-14 text-white"><div className="container-page flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-red-300">Start a Tooling Review</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">{exportPage ? "Discuss an Export Tooling Project" : "Share your tooling requirements"}</h2><p className="mt-4 max-w-3xl leading-7 text-slate-200">{exportPage ? "Share your CAD data, mold requirements, target molding machine information and customer tooling standards for engineering and export-tooling review." : "Share your CAD data, drawings and project requirements so our engineering team can review the appropriate tooling-support path."}</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link className="focus-ring inline-flex min-h-12 items-center justify-center rounded-sm bg-[var(--brand)] px-5 font-bold text-white hover:bg-[var(--brand-hover)]" href="/request-a-quote">{exportPage ? "Discuss an Export Tooling Project" : "Upload CAD for Tooling Review"} →</Link><Link className="focus-ring inline-flex min-h-12 items-center justify-center rounded-sm border border-white/70 px-5 font-bold text-white hover:bg-white hover:text-[var(--brand-dark)]" href="/injection-mold-manufacturing">View Mold Manufacturing →</Link></div></div></section>;
}

export function ToolingSupportPage({ slug }: { slug: ToolingSupportSlug }) {
  const page = toolingSupportPages[slug];
  const pageUrl = `${site.url}/injection-molds/${slug}/`;
  const secondaryHref = slug === "tooling-documentation" ? "#documentation-package" : "/request-a-quote";
  const schemas = [
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: site.url }, { "@type": "ListItem", position: 2, name: "Injection Molds", item: `${site.url}/injection-molds/` }, { "@type": "ListItem", position: 3, name: page.navLabel, item: pageUrl }] },
    { "@context": "https://schema.org", "@type": "WebPage", "@id": `${pageUrl}#webpage`, name: page.title, description: page.description, url: pageUrl, isPartOf: { "@type": "WebSite", name: site.name, url: site.url } },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: page.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }
  ];
  return <>
    {schemas.map((schema, index) => <script dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} key={index} type="application/ld+json" />)}
    <FullBleedHero backgroundImages={[{ src: page.heroImage, alt: page.heroAlt, position: slug === "export-tooling-transfer" ? "center" : "right" }]} breadcrumbs={[{ label: "Home", href: "/" }, { label: "Injection Molds", href: "/injection-molds" }, { label: page.navLabel }]} description={page.heroCopy} eyebrow={page.eyebrow} height="standard" overlay="strong" primaryCta={{ label: page.primaryCta, href: "/request-a-quote" }} secondaryCta={{ label: page.secondaryCta, href: secondaryHref }} title={page.title} />
    {slug === "mold-trial-validation" ? <TrialPage /> : null}
    {slug === "tooling-documentation" ? <DocumentationPage /> : null}
    {slug === "mold-spare-parts" ? <SparePartsPage /> : null}
    {slug === "export-tooling-transfer" ? <ExportToolingPage /> : null}
    <FaqSection slug={slug} />
    <RelatedSupport current={slug} />
    <FinalCta slug={slug} />
  </>;
}
