export type ResourceFaq = { question: string; answer: string };
export type ResourceSection = { title: string; body: string; bullets?: string[] };

export type EngineeringResource = {
  path: string;
  slug: string;
  kind: "pillar" | "article";
  topic: string;
  title: string;
  shortTitle: string;
  description: string;
  answer: string;
  image: string;
  imageAlt: string;
  takeaways: string[];
  sections: ResourceSection[];
  practical: string[];
  related: { label: string; href: string }[];
  capability: { label: string; href: string };
  caseStudy?: { label: string; href: string };
  faq?: ResourceFaq[];
};

const standardFaq = (subject: string): ResourceFaq[] => [
  { question: `When should ${subject} be reviewed?`, answer: `Review ${subject} before detailed mold design and steel cutting, while product geometry and tooling decisions can still be discussed efficiently.` },
  { question: `Can one rule be applied to every ${subject} project?`, answer: "No. Resin, part geometry, appearance, tolerance, production volume and molding conditions must be evaluated together for the specific project." }
];

export const pillarGuides: EngineeringResource[] = [
  {
    path: "/resources/dfm-guide", slug: "dfm-guide", kind: "pillar", topic: "DFM & Plastic Part Design",
    title: "Injection Molding DFM Guide for Plastic Part Design", shortTitle: "DFM Guide",
    description: "A practical injection molding DFM guide covering wall thickness, draft, ribs, bosses, undercuts, gating, ejection, materials and tooling approval.",
    answer: "Injection molding DFM connects product geometry, resin behavior and mold construction before tooling begins. The goal is to expose risks early, document open decisions and release a part definition that can be molded, inspected and assembled as intended.",
    image: "/images/Engineering/injection-mold-engineering-dfm-analysis.webp", imageAlt: "Injection molding DFM engineering review for plastic part design",
    takeaways: ["Review geometry before mold design release", "Treat wall, draft, ribs and bosses as one system", "Resolve undercuts, gating and ejection early", "Document approved risks and customer decisions"],
    sections: [
      { title: "Start with function, resin and manufacturing intent", body: "A useful DFM review begins with the product application, expected environment, resin, annual demand, appearance surfaces and critical interfaces. Geometry cannot be judged correctly without that context.", bullets: ["3D CAD and controlled 2D drawing", "Material and finish requirements", "Critical dimensions and assembly datums", "Expected volume and production location"] },
      { title: "Control wall thickness and transitions", body: "Uniform walls generally support more predictable filling, cooling and shrinkage. Thick sections, abrupt transitions and unsupported spans should be reviewed for sink, voids, warpage and cycle-time impact.", bullets: ["Core thick masses where function allows", "Use gradual transitions", "Relate rib and boss thickness to the parent wall", "Review local steel access"] },
      { title: "Design for release", body: "Draft, texture, cavity depth, pull direction and ejection work together. A surface may be manufacturable yet still be vulnerable to drag, scuffing or distortion if release conditions are weak." },
      { title: "Resolve undercuts and tooling actions", body: "External and internal undercuts may require sliders, lifters, unscrewing actions, removable inserts or a geometry change. DFM should compare the technical need with tooling complexity, maintenance and production rate." },
      { title: "Coordinate flow, venting and cosmetic surfaces", body: "Gate location, runner concept, weld lines, air traps, venting and ejector positions must be reviewed against visible surfaces and functional requirements." },
      { title: "Close the review before tooling release", body: "The strongest output is not a long report; it is a controlled set of decisions. Approved CAD, drawings, DFM comments, material assumptions and open risks should align before mold design approval." }
    ],
    practical: ["Share native or neutral 3D CAD plus the controlled drawing.", "Mark cosmetic surfaces and unacceptable witness areas.", "Identify critical-to-function dimensions instead of applying tight tolerances globally.", "Confirm resin grade and shrinkage assumptions before final cavity sizing.", "Keep customer approvals traceable through DFM and mold-design revisions."],
    related: [
      { label: "Wall Thickness Guidelines", href: "/resources/injection-molding/wall-thickness-guidelines" },
      { label: "Draft Angle Guidelines", href: "/resources/injection-molding/draft-angle-guidelines" },
      { label: "Ribs & Bosses Design", href: "/resources/injection-molding/ribs-bosses-design" },
      { label: "Undercut Design", href: "/resources/injection-molding/undercut-design" }
    ],
    capability: { label: "DFM Engineering", href: "/injection-molding-engineering" }, caseStudy: { label: "Automotive Sensor Housing Tooling", href: "/case-studies/automotive-sensor-housing-tooling" }, faq: standardFaq("injection molding DFM")
  },
  {
    path: "/resources/injection-molding-guide", slug: "injection-molding-guide", kind: "pillar", topic: "Injection Molding",
    title: "Plastic Injection Molding Guide: From Part Design to Production", shortTitle: "Injection Molding Guide",
    description: "Understand plastic injection molding from product design and material selection through tooling, trials, process validation and scalable production.",
    answer: "A controlled injection molding program links a moldable part design, suitable resin, production-ready tool, stable process window and agreed inspection plan. Decisions made before tooling strongly influence sampling effort and production consistency.",
    image: "/images/capabilities/plastic-injection-molding-production.webp", imageAlt: "Plastic injection molding production and molded component validation",
    takeaways: ["Match tooling strategy to the production program", "Validate the process, not only one good sample", "Control material handling and molding conditions", "Connect inspection with functional requirements"],
    sections: [
      { title: "How the molding cycle works", body: "Plastic is prepared, melted, injected into a closed mold, packed, cooled and ejected. Part quality reflects the interaction of material, geometry, mold design and the process settings used for each cycle." },
      { title: "Choose the production route", body: "Prototype, bridge and production tooling solve different business needs. The expected demand, design maturity, resin, surface requirements and future tool location should guide the route." },
      { title: "Prepare the mold for repeatable molding", body: "Gating, venting, cooling, ejection, wear components and maintenance access influence the process window. Trial work should identify issues and record agreed corrections." },
      { title: "Validate samples and process conditions", body: "T0 and T1 samples are engineering evidence. Review dimensions, appearance, assembly, molding conditions and remaining actions rather than approving by appearance alone." },
      { title: "Plan for scale and change control", body: "Production support benefits from controlled resin specifications, parameter records, inspection criteria, spare components and traceable engineering changes." }
    ],
    practical: ["Define whether the tool will remain at Arktech or be exported.", "Confirm resin supplier, grade, color and any regrind restrictions.", "Identify critical dimensions and cosmetic zones before trial.", "Use trial records to compare corrections and sample stages.", "Agree packaging and secondary operations before production release."],
    related: [
      { label: "Sink Marks: Causes & Solutions", href: "/resources/injection-molding/sink-marks-causes-solutions" },
      { label: "Warpage: Causes & Solutions", href: "/resources/injection-molding/warpage-causes-solutions" },
      { label: "Transparent Plastic Molding", href: "/resources/injection-molding/transparent-plastic-molding" },
      { label: "Engineering Plastics Guide", href: "/resources/injection-molding/engineering-plastics-guide" }
    ],
    capability: { label: "Plastic Injection Molding", href: "/plastic-injection-molding" }, caseStudy: { label: "Smart Home Plastic Housing", href: "/case-studies/smart-home-plastic-housing" }, faq: standardFaq("plastic injection molding")
  },
  {
    path: "/resources/material-selection-guide", slug: "material-selection-guide", kind: "pillar", topic: "Materials",
    title: "Plastic Material Selection Guide for Injection Molding", shortTitle: "Material Selection Guide",
    description: "Compare thermoplastic material families for injection molding by function, environment, appearance, processing behavior and dimensional needs.",
    answer: "Material selection should begin with product requirements rather than a familiar resin name. Mechanical load, temperature, chemicals, moisture, appearance, regulatory needs, tolerance and assembly method all influence the correct grade and tooling strategy.",
    image: "/images/material-capabilities/engineering-plastic-parts-abs-pc-pa-pom.webp", imageAlt: "Engineering plastic parts manufactured from common thermoplastic material families",
    takeaways: ["Select a specific grade, not only a polymer family", "Balance performance with molding behavior", "Consider moisture, fillers and shrinkage", "Validate color, finish and assembly requirements"],
    sections: [
      { title: "Translate product requirements into material criteria", body: "Document load, impact, service temperature, chemical exposure, UV, flame behavior, transparency, color, finish, dimensional stability and cost priorities before comparing resin families." },
      { title: "Commodity and general engineering plastics", body: "PP, ABS, PC, PC/ABS, POM, PA and PBT cover many housings and functional components, but grade-level properties and processing requirements vary significantly." },
      { title: "High-performance thermoplastics", body: "PPS, PPSU and PEEK can support demanding temperature, chemical or mechanical requirements when the application and actual processing capability justify them. Tool temperature, material drying, wear and validation need project-specific planning." },
      { title: "Reinforcement changes the system", body: "Glass fiber can increase stiffness and alter shrinkage, flow, surface appearance, wear and anisotropy. Part geometry, gate direction and critical dimensions should be reviewed for the selected filled grade." },
      { title: "Approve the grade before final tooling decisions", body: "Avoid sizing a mold around an approximate resin family when the final grade can materially change shrinkage and processing behavior." }
    ],
    practical: ["Provide the exact supplier and grade when specified.", "State whether recycled content or regrind is permitted.", "Mark appearance and color-critical surfaces.", "Identify chemical, UV, sterilization or temperature exposure.", "Review mating materials and joining processes."],
    related: [
      { label: "Engineering Plastics Guide", href: "/resources/injection-molding/engineering-plastics-guide" },
      { label: "PPS vs PBT vs PA", href: "/resources/materials/pps-vs-pbt-vs-pa" },
      { label: "Transparent Plastic Molding", href: "/resources/injection-molding/transparent-plastic-molding" },
      { label: "Injection Molding Guide", href: "/resources/injection-molding-guide" }
    ],
    capability: { label: "Plastic Injection Molding", href: "/plastic-injection-molding" }, caseStudy: { label: "Medical Device Cartridge Molding", href: "/case-studies/medical-device-cartridge-molding" }, faq: standardFaq("plastic material selection")
  },
  {
    path: "/resources/mold-design-guidelines", slug: "mold-design-guidelines", kind: "pillar", topic: "Injection Mold Design",
    title: "Injection Mold Design Guidelines for Export Tooling", shortTitle: "Mold Design Guidelines",
    description: "Engineering guidance for injection mold layout, steel, gating, cooling, ejection, mold actions, hot runners, validation and export documentation.",
    answer: "Export mold design must connect the molded part, customer machine and production standard. The design should make gate, cooling, ejection, actions, wear components, maintenance access and approved standards visible before manufacturing release.",
    image: "/images/mold-types/complex-injection-molds.png", imageAlt: "Complex export injection mold design with multiple tooling actions",
    takeaways: ["Design around the receiving molder's standards", "Review the complete mold motion and maintenance path", "Balance filling, cooling and ejection", "Release manufacturing only after approval"],
    sections: [
      { title: "Define the mold specification", body: "Confirm press interface, mold base standard, steel, cavitation, runner system, connector standards, cycle expectations, resin and export destination before detailed design." },
      { title: "Establish parting, gating and cavity layout", body: "Parting lines, cavity orientation and gate locations affect filling, cosmetics, trimming, balance and mold construction. Multi-cavity tools also require balanced delivery and consistent thermal conditions." },
      { title: "Plan cooling and ejection", body: "Cooling access should support controlled heat removal around critical geometry. Ejection must release the part without unacceptable marks or distortion and remain serviceable in production." },
      { title: "Engineer sliders, lifters and unscrewing actions", body: "Tool actions require positive guidance, travel, locking, wear planning and sequence review. The simplest reliable mechanism that meets product needs is generally preferred." },
      { title: "Approve and document the mold", body: "The customer review should capture the mold layout, actions, gate, cooling, ejection, components and interfaces. Final records support trial, maintenance and transfer." }
    ],
    practical: ["Share the destination press and interface requirements.", "Confirm DME, Meusburger or customer component standards where required.", "Identify hot-runner brand and spare requirements.", "Review mold movements and safety conditions before release.", "Include final 2D/3D records and parts lists in the export package."],
    related: [
      { label: "Hot Runner vs Cold Runner", href: "/resources/injection-molds/hot-runner-vs-cold-runner" },
      { label: "Multi-Cavity vs Family Mold", href: "/resources/injection-molds/multi-cavity-vs-family-mold" },
      { label: "Slider vs Lifter", href: "/resources/injection-molds/slider-vs-lifter" },
      { label: "Undercut Design", href: "/resources/injection-molding/undercut-design" }
    ],
    capability: { label: "Injection Mold Manufacturing", href: "/injection-mold-manufacturing" }, caseStudy: { label: "Automotive Sensor Housing Tooling", href: "/case-studies/automotive-sensor-housing-tooling" }, faq: standardFaq("injection mold design")
  }
];

function article(input: Omit<EngineeringResource, "kind" | "faq"> & { faq?: ResourceFaq[] }): EngineeringResource {
  return { ...input, kind: "article", faq: input.faq ?? standardFaq(input.shortTitle.toLowerCase()) };
}

export const resourceArticles: EngineeringResource[] = [
  article({ path: "/resources/injection-molding/wall-thickness-guidelines", slug: "wall-thickness-guidelines", topic: "DFM & Plastic Part Design", title: "Injection Molding Wall Thickness Guidelines", shortTitle: "Wall Thickness Guidelines", description: "How uniform walls, gradual transitions and local feature thickness influence filling, cooling, sink and warpage in injection molded parts.", answer: "Uniform wall thickness helps plastic fill and cool more consistently. The correct thickness is material- and geometry-dependent, so transitions, ribs, bosses and heavy sections should be reviewed together rather than against one universal value.", image: "/images/process/dfm-engineering-feedback-old-website.png", imageAlt: "DFM review of wall thickness in an injection molded plastic part", takeaways: ["Favor consistent walls", "Core out heavy sections", "Use gradual transitions", "Confirm limits for the selected resin"], sections: [{ title: "Why wall uniformity matters", body: "Different section thicknesses cool and shrink at different rates, increasing the risk of sink, internal stress, warpage and extended cycle time." }, { title: "Treat transitions carefully", body: "When thickness must change, a gradual transition generally produces a smoother flow and cooling condition than an abrupt step." }, { title: "Connect ribs and bosses to the parent wall", body: "Reinforcement and assembly features should provide function without creating local masses directly behind visible surfaces." }], practical: ["Review nominal walls on the 3D model.", "Mark cosmetic A-surfaces.", "Check long flow paths and thin restrictions.", "Evaluate thick bosses and intersections."], related: [{ label: "Ribs & Bosses Design", href: "/resources/injection-molding/ribs-bosses-design" }, { label: "Sink Marks", href: "/resources/injection-molding/sink-marks-causes-solutions" }], capability: { label: "DFM Engineering", href: "/injection-molding-engineering" } }),
  article({ path: "/resources/injection-molding/draft-angle-guidelines", slug: "draft-angle-guidelines", topic: "DFM & Plastic Part Design", title: "Draft Angle Guidelines for Injection Molded Parts", shortTitle: "Draft Angle Guidelines", description: "Understand how pull direction, depth, texture, resin and cosmetic requirements affect draft for reliable molded-part release.", answer: "Draft reduces friction as a molded part leaves the core or cavity. Required draft depends on depth, texture, resin shrinkage, steel finish and acceptable appearance, so every pull surface should be reviewed in context.", image: "/images/Engineering/injection-mold-engineering-dfm-analysis.webp", imageAlt: "Injection molding draft angle and pull direction engineering review", takeaways: ["Define the pull direction", "Increase draft for deeper or textured surfaces", "Protect visible faces from drag", "Coordinate draft with shutoffs"], sections: [{ title: "Draft supports release", body: "Near-vertical faces can retain the part and create drag marks, whitening, distortion or ejection load." }, { title: "Texture changes the requirement", body: "Texture depth and pattern increase mechanical engagement with the steel. The draft requirement should be confirmed with the selected texture standard." }, { title: "Review internal and external faces", body: "Core-side and cavity-side faces may need different treatment based on shrinkage, depth and desired part retention." }], practical: ["Apply draft in the correct opening direction.", "Confirm texture before final geometry approval.", "Check deep bosses, ribs and pockets.", "Review shutoff angles separately."], related: [{ label: "Undercut Design", href: "/resources/injection-molding/undercut-design" }, { label: "DFM Guide", href: "/resources/dfm-guide" }], capability: { label: "DFM Engineering", href: "/injection-molding-engineering" } }),
  article({ path: "/resources/injection-molding/ribs-bosses-design", slug: "ribs-bosses-design", topic: "DFM & Plastic Part Design", title: "Ribs and Bosses Design for Injection Molding", shortTitle: "Ribs & Bosses Design", description: "Design ribs, gussets and screw bosses for stiffness and assembly while managing sink, filling, draft and local stress.", answer: "Ribs and bosses should add stiffness or assembly function without becoming thick material masses. Their thickness, height, draft, radii, spacing and connection to the nominal wall should be reviewed together.", image: "/images/capabilities/injection-mold-engineering-dfm-analysis.webp", imageAlt: "DFM engineering review of ribs and bosses for injection molding", takeaways: ["Keep local mass controlled", "Add draft and root radii", "Support bosses without heavy intersections", "Validate fastening loads"], sections: [{ title: "Use ribs for stiffness", body: "Ribs can improve bending stiffness without uniformly thickening the part, but poor proportions can create sink, difficult filling or tool-access problems." }, { title: "Design bosses around the assembly", body: "Boss geometry depends on screws, inserts, torque, mating parts and load path. Unsupported tall bosses are vulnerable to deformation and breakage." }, { title: "Check mold access and ejection", body: "Deep, narrow features require adequate steel, venting, draft and reliable release." }], practical: ["Relate rib and boss thickness to the parent wall.", "Avoid overlapping heavy intersections.", "Provide root radii and draft.", "Test the intended screw or insert system."], related: [{ label: "Wall Thickness Guidelines", href: "/resources/injection-molding/wall-thickness-guidelines" }, { label: "DFM Guide", href: "/resources/dfm-guide" }], capability: { label: "DFM Engineering", href: "/injection-molding-engineering" } }),
  article({ path: "/resources/injection-molding/undercut-design", slug: "undercut-design", topic: "DFM & Plastic Part Design", title: "Undercut Design for Injection Molded Parts", shortTitle: "Undercut Design", description: "Compare sliders, lifters, unscrewing actions, inserts and geometry changes for internal, external and threaded undercuts.", answer: "An undercut prevents straight-line part release. The right solution depends on feature direction, travel, part flexibility, production volume, appearance, tolerance and acceptable mold complexity.", image: "/images/mold-types/unscrewing-molds.webp", imageAlt: "Injection mold mechanism for releasing threaded and undercut plastic features", takeaways: ["Identify every blocked pull direction", "Compare geometry changes before adding actions", "Select the simplest reliable mechanism", "Plan wear and maintenance"], sections: [{ title: "Classify the undercut", body: "External features often suit sliders, internal features may suit lifters, and threaded features may require collapsible or unscrewing mechanisms." }, { title: "Consider product redesign", body: "A shutoff, access opening, split feature or assembly change can sometimes remove a tool action while preserving function." }, { title: "Engineer the motion", body: "Travel, locking, guidance, timing, lubrication and replaceable wear areas must be resolved before mold manufacture." }], practical: ["Mark the primary pull direction.", "Check action travel and interference.", "Review witness lines and cosmetic impact.", "Include action components in maintenance records."], related: [{ label: "Slider vs Lifter", href: "/resources/injection-molds/slider-vs-lifter" }, { label: "Mold Design Guidelines", href: "/resources/mold-design-guidelines" }], capability: { label: "Injection Mold Manufacturing", href: "/injection-mold-manufacturing" }, caseStudy: { label: "Unscrewing Threaded Component Mold", href: "/case-studies/unscrewing-threaded-component-mold" } }),
  article({ path: "/resources/injection-molds/hot-runner-vs-cold-runner", slug: "hot-runner-vs-cold-runner", topic: "Injection Mold Design", title: "Hot Runner vs Cold Runner Injection Molds", shortTitle: "Hot Runner vs Cold Runner", description: "Compare hot and cold runner mold strategies by material, cavitation, part quality, maintenance, resin waste and production needs.", answer: "Cold runners are mechanically simpler and produce a solid runner with each cycle; hot runners keep melt channels heated and can reduce runner waste. The right system depends on resin sensitivity, gate needs, cavitation, maintenance capability and production economics.", image: "/images/mold-types/hot-runner-molds.webp", imageAlt: "Hot runner injection mold and plastic production components", takeaways: ["Evaluate total production economics", "Confirm resin compatibility", "Review gate vestige and balance", "Plan spares and maintenance"], sections: [{ title: "Cold runner strengths", body: "Cold runners can simplify tooling and material changeover, but runners add material handling and may increase shot size." }, { title: "Hot runner strengths", body: "Hot runners can support higher cavitation and reduced runner waste, but add thermal-control, component and maintenance requirements." }, { title: "Make the choice with the molder", body: "The receiving plant should confirm controller, connector, service and preferred supplier standards before release." }], practical: ["Confirm resin and color-change needs.", "Compare runner waste with maintenance cost.", "Review thermal balance and gate type.", "Specify spare heaters, thermocouples and tips as applicable."], related: [{ label: "Multi-Cavity vs Family Mold", href: "/resources/injection-molds/multi-cavity-vs-family-mold" }, { label: "Mold Design Guidelines", href: "/resources/mold-design-guidelines" }], capability: { label: "Injection Mold Manufacturing", href: "/injection-mold-manufacturing" } }),
  article({ path: "/resources/injection-molds/multi-cavity-vs-family-mold", slug: "multi-cavity-vs-family-mold", topic: "Injection Mold Design", title: "Multi-Cavity Mold vs Family Mold", shortTitle: "Multi-Cavity vs Family Mold", description: "Understand when identical multi-cavity tooling or a family mold with different parts better fits production demand and assembly needs.", answer: "A multi-cavity mold produces several copies of the same part per cycle. A family mold produces different related parts. Family tools can consolidate tooling but require balanced filling, compatible part volumes and a practical approach to unequal demand.", image: "/images/mold-types/multi-cavity-injection-molds.webp", imageAlt: "Multi-cavity injection mold for stable production of repeated plastic components", takeaways: ["Match cavitation to demand", "Check flow and cooling balance", "Compare unequal part consumption", "Protect quality across every cavity"], sections: [{ title: "Multi-cavity production", body: "Identical cavities can increase output, but cavity-to-cavity balance and consistent cooling are central validation requirements." }, { title: "Family mold tradeoffs", body: "Related parts can share one mold, but different size, thickness, gate need and consumption ratio may complicate the process." }, { title: "Plan inspection by cavity", body: "Samples and measurements should remain traceable to each cavity during validation and production." }], practical: ["Compare annual volume with machine and cycle assumptions.", "Review cavity balance and part identification.", "Avoid family combinations with incompatible molding windows.", "Plan cavity-specific inspection records."], related: [{ label: "Hot Runner vs Cold Runner", href: "/resources/injection-molds/hot-runner-vs-cold-runner" }, { label: "Mold Design Guidelines", href: "/resources/mold-design-guidelines" }], capability: { label: "Injection Mold Manufacturing", href: "/injection-mold-manufacturing" }, caseStudy: { label: "Automotive Multi-Cavity Mold", href: "/case-studies/automotive-sensor-housing-tooling" } }),
  article({ path: "/resources/injection-molds/slider-vs-lifter", slug: "slider-vs-lifter", topic: "Injection Mold Design", title: "Slider vs Lifter in Injection Mold Design", shortTitle: "Slider vs Lifter", description: "Compare sliders and lifters for releasing external and internal undercuts in injection mold design.", answer: "A slider generally moves laterally to release an external undercut. A lifter moves at an angle during ejection to release an internal feature. Selection depends on feature direction, travel, available steel, ejection sequence and production reliability.", image: "/images/case-studies/fan-blade-mold.webp", imageAlt: "Complex injection mold with multiple sliders and lifters", takeaways: ["Follow the undercut direction", "Confirm movement and clearance", "Protect shutoffs and wear areas", "Review sequence and service access"], sections: [{ title: "When a slider fits", body: "Sliders are often used for side holes, clips and external features that can be released with lateral movement before ejection." }, { title: "When a lifter fits", body: "Lifters can release internal hooks or recesses while participating in ejection, but they require angle, stroke and guidance review." }, { title: "Reliability is more than geometry", body: "Locking, return, wear, lubrication, replaceability and sensing can be as important as the initial mechanism choice." }], practical: ["Model the full motion path.", "Check steel thickness around the action.", "Define shutoff contact and wear inserts.", "Include service parts in the mold record."], related: [{ label: "Undercut Design", href: "/resources/injection-molding/undercut-design" }, { label: "Mold Design Guidelines", href: "/resources/mold-design-guidelines" }], capability: { label: "Injection Mold Manufacturing", href: "/injection-mold-manufacturing" } }),
  article({ path: "/resources/injection-molding/sink-marks-causes-solutions", slug: "sink-marks-causes-solutions", topic: "Defects & Troubleshooting", title: "Injection Molding Sink Marks: Causes and Solutions", shortTitle: "Sink Marks: Causes & Solutions", description: "Identify geometry, packing, cooling and material factors behind sink marks in injection molded parts and review corrective options.", answer: "Sink marks appear when a local region shrinks after the outer surface has set, commonly near thick sections, ribs and bosses. Correction may involve geometry, gate and packing, cooling, material or process changes.", image: "/images/process/sample-validation-inspection-cmm.png", imageAlt: "Inspection of injection molded samples for dimensional and cosmetic defects", takeaways: ["Locate hidden thick sections", "Review pack path and gate freeze", "Improve local cooling balance", "Treat process and geometry together"], sections: [{ title: "Geometry-driven sink", body: "Heavy intersections and thick bases cool slowly and draw material inward. Coring and better-proportioned features can reduce the local mass." }, { title: "Process-driven sink", body: "Insufficient packing, early gate freeze or an unsuitable process window can contribute, but process changes should not mask a weak part design." }, { title: "Validate the correction", body: "Compare sample stages under recorded conditions and inspect both cosmetic surfaces and functional dimensions." }], practical: ["Map sink to the opposite-side feature.", "Review rib and boss bases.", "Check gate location and packing path.", "Record settings for before-and-after trials."], related: [{ label: "Wall Thickness Guidelines", href: "/resources/injection-molding/wall-thickness-guidelines" }, { label: "Warpage Causes & Solutions", href: "/resources/injection-molding/warpage-causes-solutions" }], capability: { label: "Mold Trial & Validation", href: "/injection-molds/mold-trial-validation" } }),
  article({ path: "/resources/injection-molding/warpage-causes-solutions", slug: "warpage-causes-solutions", topic: "Defects & Troubleshooting", title: "Injection Molding Warpage: Causes and Solutions", shortTitle: "Warpage: Causes & Solutions", description: "Understand how geometry, fiber orientation, shrinkage, cooling, packing and ejection can distort injection molded parts.", answer: "Warpage results from non-uniform shrinkage and internal stress. Part geometry, gate direction, cooling, resin orientation, packing and release conditions should be reviewed as a connected system.", image: "/images/process/sample-validation-inspection-cmm.png", imageAlt: "Molded part dimensional inspection used to evaluate injection molding warpage", takeaways: ["Measure against controlled datums", "Review directional shrinkage", "Balance cooling and filling", "Avoid relying on one process adjustment"], sections: [{ title: "Geometry and shrinkage", body: "Uneven walls, asymmetric shapes and unsupported areas can shrink differently and pull a part out of nominal form." }, { title: "Material orientation", body: "Filled materials can shrink differently along and across flow, making gate direction and part layout especially important." }, { title: "Tool and process contributors", body: "Cooling imbalance, uneven packing and premature or unbalanced ejection can add distortion." }], practical: ["Define the measurement fixture and conditioning time.", "Compare flow direction with deformation.", "Review cooling around heavy geometry.", "Track trial changes one variable set at a time."], related: [{ label: "Wall Thickness Guidelines", href: "/resources/injection-molding/wall-thickness-guidelines" }, { label: "Injection Molding Guide", href: "/resources/injection-molding-guide" }], capability: { label: "Mold Trial & Validation", href: "/injection-molds/mold-trial-validation" } }),
  article({ path: "/resources/injection-molding/transparent-plastic-molding", slug: "transparent-plastic-molding", topic: "Injection Molding", title: "Transparent Plastic Injection Molding", shortTitle: "Transparent Plastic Molding", description: "Engineering considerations for transparent molded parts, including resin handling, polishing, flow, gate vestige and cosmetic inspection.", answer: "Transparent parts make flow, contamination, weld lines, scratches, ejector marks and polishing quality highly visible. Success depends on confirmed resin, clean material handling, suitable tool finish and clear cosmetic acceptance criteria.", image: "/images/case-studies/two-shot-light-cover.webp", imageAlt: "Transparent molded plastic light cover and precision tooling project", takeaways: ["Define optical and cosmetic needs", "Protect polished steel and parts", "Control material preparation", "Agree visual inspection conditions"], sections: [{ title: "Clarify transparency requirements", body: "A clear protective cover and an optical component have different needs. Define haze, visual zones, distortion and functional light transmission as applicable." }, { title: "Design the gate and flow path", body: "Gate vestige, weld lines and flow marks should be reviewed against visible and optical zones." }, { title: "Protect the surface", body: "Tool polishing, handling, packaging and secondary assembly can all introduce visible damage." }], practical: ["Specify the exact transparent resin grade.", "Mark critical optical and cosmetic zones.", "Agree lighting and viewing conditions.", "Protect parts through packing and assembly."], related: [{ label: "Material Selection Guide", href: "/resources/material-selection-guide" }, { label: "Injection Molding Guide", href: "/resources/injection-molding-guide" }], capability: { label: "Plastic Injection Molding", href: "/plastic-injection-molding" }, caseStudy: { label: "Two-Shot Light Cover Tooling", href: "/case-studies/two-shot-2k-injection-mold-tooling" } }),
  article({ path: "/resources/injection-molding/engineering-plastics-guide", slug: "engineering-plastics-guide", topic: "Materials", title: "Engineering Plastics Injection Molding Guide", shortTitle: "Engineering Plastics Guide", description: "A practical guide to molding engineering plastics, reinforced grades and higher-performance thermoplastics for functional components.", answer: "Engineering plastics are selected for performance, but they also bring specific drying, mold-temperature, shrinkage, flow, wear and handling requirements. The exact supplier grade must be reviewed before final tooling decisions.", image: "/images/material-capabilities/engineering-plastic-parts-abs-pc-pa-pom.webp", imageAlt: "Injection molded engineering plastic components in multiple functional material families", takeaways: ["Work from a verified grade", "Control drying and handling", "Account for fillers and directional shrinkage", "Match tooling to temperature and wear"], sections: [{ title: "Common engineering families", body: "PC, PC/ABS, PA, PBT and POM serve many functional components. PPS, PPSU and PEEK address more demanding applications only when verified requirements and processing capability support them." }, { title: "Moisture and thermal history", body: "Hygroscopic resins require controlled preparation. Poor drying or excessive residence can affect appearance and material performance." }, { title: "Filled grades", body: "Glass and mineral reinforcement change stiffness, flow, wear, appearance and shrinkage behavior." }], practical: ["Confirm manufacturer and full grade code.", "Review drying and storage requirements.", "Consider tool-steel wear for filled materials.", "Plan dimensional validation after conditioning where relevant."], related: [{ label: "PPS vs PBT vs PA", href: "/resources/materials/pps-vs-pbt-vs-pa" }, { label: "Material Selection Guide", href: "/resources/material-selection-guide" }], capability: { label: "Plastic Injection Molding", href: "/plastic-injection-molding" } }),
  article({ path: "/resources/materials/pps-vs-pbt-vs-pa", slug: "pps-vs-pbt-vs-pa", topic: "Materials", title: "PPS vs PBT vs PA for Injection Molded Parts", shortTitle: "PPS vs PBT vs PA", description: "Compare PPS, PBT and polyamide material families by temperature, moisture, dimensional behavior, chemical exposure and processing considerations.", answer: "PPS, PBT and PA are not interchangeable. PPS is considered for demanding thermal and chemical conditions; PBT can support dimensional and electrical applications; PA offers broad mechanical performance but moisture response requires attention. Grade-level data and application testing remain essential.", image: "/images/material-capabilities/Engineering-Plastic-Parts.webp", imageAlt: "Engineering plastic molded parts for PPS PBT and PA material comparison", takeaways: ["Compare specific grades", "Include moisture and conditioning", "Review fillers and flow orientation", "Validate the real service environment"], sections: [{ title: "PPS", body: "PPS grades are considered where heat, chemicals, dimensional stability or flame requirements justify a higher-performance resin and corresponding processing controls." }, { title: "PBT", body: "PBT grades are widely evaluated for electrical, automotive and dimensional applications; hydrolysis, impact and filled-grade behavior should be checked for the use case." }, { title: "PA / nylon", body: "PA families offer useful strength and wear performance, but moisture absorption can change dimensions and properties. Conditioning and actual environment matter." }], practical: ["Compare supplier datasheets under relevant conditions.", "Specify filler type and percentage.", "Review moisture exposure and conditioning.", "Run functional validation on production-intent material."], related: [{ label: "Engineering Plastics Guide", href: "/resources/injection-molding/engineering-plastics-guide" }, { label: "Material Selection Guide", href: "/resources/material-selection-guide" }], capability: { label: "Plastic Injection Molding", href: "/plastic-injection-molding" } })
];

export const allEngineeringResources = [...pillarGuides, ...resourceArticles];
export const engineeringResourceByPath = new Map(allEngineeringResources.map((item) => [item.path, item]));
export const articleByCategory = new Map<string, EngineeringResource[]>([
  ["injection-molding", resourceArticles.filter((item) => item.path.startsWith("/resources/injection-molding/"))],
  ["injection-molds", resourceArticles.filter((item) => item.path.startsWith("/resources/injection-molds/"))],
  ["materials", resourceArticles.filter((item) => item.path.startsWith("/resources/materials/"))]
]);
