export type IndustryItem = readonly [title: string, body: string];
export type IndustryLinkItem = { title: string; body: string; href: string };
export type IndustryMoldType = { title: string; body: string; href?: string };
export type IndustryFaq = readonly [question: string, answer: string];
export type IndustryEvidence = {
  eyebrow: string; title: string; summary: string; image: string; alt: string;
  application: string; engineeringFocus: string; validation: string;
  href?: string; linkLabel?: string;
};
export type IndustryLandingPageData = {
  slug: string; navTitle: string; eyebrow: string; seoTitle: string; metaDescription: string;
  h1: string; heroCopy: string; heroImage: string; heroAlt: string;
  heroPosition?: "center" | "right" | "top"; secondaryCta: string;
  applicationImage: string; applicationAlt: string; applicationsHeading: string;
  applicationsIntro: string; applications: IndustryItem[];
  engineeringHeading: string; engineeringIntro: string; engineeringConsiderations: IndustryItem[];
  toolingHeading: string; toolingIntro: string; toolingConsiderations: IndustryItem[];
  moldTypesIntro: string; moldTypes: IndustryMoldType[]; evidence: IndustryEvidence;
  processIntro: string; validationHeading: string; validationIntro: string;
  validationItems: IndustryItem[]; resources: IndustryLinkItem[];
  relatedCapabilities: IndustryLinkItem[]; faqs: IndustryFaq[];
  ctaEyebrow: string; ctaHeading: string; ctaCopy: string;
  needsAssetReplacement?: boolean; assetReplacementNote?: string;
};

const mold = {
  precision: { title: "Precision Injection Molds", body: "Controlled tooling for repeatable dimensions, assembly datums and stable production.", href: "/injection-molds/precision-injection-molds" },
  complex: { title: "Complex Injection Molds", body: "Coordinated sliders, lifters and shutoffs for difficult release geometry.", href: "/injection-molds/complex-injection-molds" },
  multi: { title: "Multi-Cavity Injection Molds", body: "Balanced cavitation for repeated components and production output.", href: "/injection-molds/multi-cavity-molds" },
  hot: { title: "Hot Runner Molds", body: "Runner concepts reviewed around resin, gate location, appearance and volume.", href: "/injection-molds/hot-runner-molds" },
  insert: { title: "Insert Molding Tools", body: "Tooling for molded parts with integrated metal or functional inserts.", href: "/injection-molds/insert-molding-tools" },
  over: { title: "Overmolding Tools", body: "Tooling for integrated grip, protection, sealing or multi-material features.", href: "/injection-molds/overmolding-tools" },
  twoK: { title: "Two-Shot / 2K Molds", body: "Multi-material tooling for integrated interfaces, controls and visible features.", href: "/injection-molds/two-shot-2k-molds" },
  large: { title: "Large Injection Molds", body: "Large-format tooling for structural housings, covers and visible panels.", href: "/injection-molds/large-injection-molds" },
  unscrewing: { title: "Unscrewing Molds", body: "Mechanically released tooling for molded threads and rotational undercuts.", href: "/injection-molds/unscrewing-molds" }
} satisfies Record<string, IndustryMoldType>;

const caps = (industry: string): IndustryLinkItem[] => [
  { title: "Injection Mold Manufacturing", body: `Export tooling developed around ${industry} product, machine and validation requirements.`, href: "/services/injection-mold-manufacturing" },
  { title: "Plastic Injection Molding", body: "Engineering samples, low-volume builds and repeat molded-part supply after approval.", href: "/services/plastic-injection-molding" },
  { title: "DFM & Injection Molding Engineering", body: "Review geometry, material intent, assembly interfaces and tooling risks before release.", href: "/injection-molding-engineering" },
  { title: "Mold Trial & Validation", body: "Document samples, process conditions, inspection results and correction actions.", href: "/injection-molds/mold-trial-validation" }
];

const resource = {
  dfm: { title: "DFM Guide", body: "Prepare geometry, requirements and risk items before tooling release.", href: "/resources/dfm-guide" },
  material: { title: "Material Selection Guide", body: "Compare resin families against product and manufacturing requirements.", href: "/resources/material-selection-guide" },
  ribs: { title: "Ribs & Bosses Design", body: "Plan stiffness and fastening features without unnecessary local mass.", href: "/resources/injection-molding/ribs-bosses-design" },
  draft: { title: "Draft Angle Guidelines", body: "Coordinate part release with depth, texture and visible surfaces.", href: "/resources/injection-molding/draft-angle-guidelines" },
  warpage: { title: "Warpage: Causes & Solutions", body: "Connect geometry, shrinkage, gate direction and cooling to distortion.", href: "/resources/injection-molding/warpage-causes-solutions" },
  transparent: { title: "Transparent Plastic Molding", body: "Review resin, polish, flow and visual criteria for clear parts.", href: "/resources/injection-molding/transparent-plastic-molding" },
  engineering: { title: "Engineering Plastics Guide", body: "Review reinforced and performance resins using the exact supplier grade.", href: "/resources/injection-molding/engineering-plastics-guide" },
  slider: { title: "Slider vs Lifter", body: "Compare release mechanisms for external and internal undercuts.", href: "/resources/injection-molds/slider-vs-lifter" },
  multi: { title: "Multi-Cavity vs Family Mold", body: "Compare cavitation strategies against balance, demand and part mix.", href: "/resources/injection-molds/multi-cavity-vs-family-mold" }
} satisfies Record<string, IndustryLinkItem>;

export const industryProcess = [
  ["01", "Product & RFQ Review"], ["02", "DFM & Mold Concept"],
  ["03", "Mold Design & Approval"], ["04", "Tooling & Mold Trial"],
  ["05", "Sample Validation"], ["06", "Production & Delivery"]
] as const;

export const industryLandingPages: IndustryLandingPageData[] = [
  {
    slug: "smart-home-iot", navTitle: "Smart Home & IoT", eyebrow: "SMART HOME & IOT",
    seoTitle: "Smart Home & IoT Injection Molding & Tooling | Arktech",
    metaDescription: "Custom injection molds and plastic injection molding for smart home and IoT products including housings, controls, connected devices and functional plastic components.",
    h1: "Injection Molding & Tooling for Smart Home & IoT Products",
    heroCopy: "Engineering, tooling and molded plastic components for connected devices where appearance, assembly, dimensional fit and scalable production matter.",
    heroImage: "/images/industries/smart-device-housings.png",
    heroAlt: "Smart home cameras hubs controls and sensors with molded plastic housings",
    secondaryCta: "Discuss a Smart Home Project",
    applicationImage: "/images/industries/smart-iot-device-housings.jpg",
    applicationAlt: "Connected home controls sensors hubs and camera housings",
    applicationsHeading: "Smart Home & Connected-Device Applications",
    applicationsIntro: "Support spans visible enclosures and the functional features used to package electronics and assemble connected products.",
    applications: [["Smart Hubs & Gateways", "Housings with PCB mounts, ports, ventilation and controlled gaps."], ["Cameras & Sensors", "Compact enclosures with optical openings and locating features."], ["Smart Locks & Controls", "Visible covers, buttons and carriers for connected access products."], ["Routers & Network Devices", "Ventilated housings with cable access and internal supports."], ["Connected Accessories", "Bases, cradles and functional parts designed for repeated assembly."]],
    engineeringHeading: "Engineering Priorities for Connected Product Housings",
    engineeringIntro: "Smart-product housings combine a visible consumer surface with dense internal electronics and frequent assembly operations.",
    engineeringConsiderations: [["Cosmetic Surface Control", "Coordinate texture, polish, gate vestige and parting lines around visible zones."], ["PCB & Connector Packaging", "Review bosses, ports and clearances against the real electronic assembly."], ["Snap-Fit Reliability", "Balance retention, service access and molding stress around repeated assembly."], ["Optical Features", "Protect light paths and camera openings from avoidable weld lines and distortion."], ["Gap & Flush Interfaces", "Define datums and tolerances across mating covers, bezels and bases."], ["Ventilation Geometry", "Review thin slots for filling, steel strength and release."]],
    toolingHeading: "Tooling & Molding Considerations for Smart Devices",
    toolingIntro: "Tool design is aligned with appearance zones, internal interfaces, material behavior and intended production scale.",
    toolingConsiderations: [["Gate strategy", "Keep gates away from priority cosmetic and optical areas where practical."], ["Shutoffs & side actions", "Release ports, hooks and switch openings with serviceable mechanisms."], ["Texture & polishing", "Confirm finish requirements before final steel and sample acceptance."], ["Warpage control", "Balance walls, ribs, gate direction and cooling around broad enclosure surfaces."], ["Assembly validation", "Check PCB, connector and mating-part interfaces during sample approval."]],
    moldTypesIntro: "Connected-device programs commonly use precision, complex, multi-cavity and multi-material tooling.",
    moldTypes: [mold.precision, mold.complex, mold.multi, mold.twoK],
    evidence: { eyebrow: "REAL PROJECT EVIDENCE", title: "Smart Home Housing Tooling Project", summary: "A documented housing program connecting DFM review, appearance requirements, assembly features and mold validation.", image: "/images/case-studies/smart-home-iot-project.webp", alt: "Smart home IoT housing project with molded enclosure components and assembly evidence", application: "Connected-device enclosure and mating housing components", engineeringFocus: "Visible surfaces, snap-fit assembly and controlled gaps", validation: "Molded samples reviewed for appearance, dimensions and assembly fit", href: "/case-studies/smart-home-plastic-housing", linkLabel: "View Smart Home Housing Project" },
    processIntro: "The development path keeps appearance, electronic interfaces and production requirements connected from CAD review through repeat molding.",
    validationHeading: "Validation for Smart Home Housings & Assemblies",
    validationIntro: "Approval focuses on the visible and functional interfaces that determine product assembly and user-facing quality.",
    validationItems: [["Cosmetic review", "Inspect agreed visible zones, texture and allowable molding marks."], ["Gap & flush check", "Review mating covers and bezels against interface criteria."], ["PCB / connector fit", "Confirm mounts, ports and clearances with representative hardware."], ["Critical dimensions", "Record drawing dimensions that control assembly or function."], ["Process records", "Retain agreed molding parameters and sample status for release review."]],
    resources: [resource.ribs, resource.draft, resource.material], relatedCapabilities: caps("smart home and IoT"),
    faqs: [["What smart home parts can Arktech support?", "Programs can include hubs, gateways, cameras, sensors, smart locks, routers, controls and connected-product housings."], ["Can DFM include PCB and connector data?", "Yes. Representative electronics and mating parts help review bosses, ports, clearances and datums before tooling release."], ["How are visible surfaces controlled?", "Appearance zones, texture, gates, parting lines and allowed witness marks are agreed before mold approval and reviewed during trials."], ["Can Arktech support low-volume and repeat production?", "Projects can progress from engineering samples and low-volume builds into repeat molding after approval."]],
    ctaEyebrow: "SMART HOME & IOT RFQ", ctaHeading: "Discuss Your Smart Home or IoT Application", ctaCopy: "Send CAD, material targets, finish requirements, expected volume and electronic or mating-part data for engineering review."
  },
  {
    slug: "home-appliances", navTitle: "Home Appliances", eyebrow: "HOME APPLIANCES",
    seoTitle: "Home Appliance Injection Molding & Plastic Tooling | Arktech",
    metaDescription: "Injection molds and molded plastic components for home appliance housings, panels, controls and structural parts with focus on appearance, fit, warpage and production consistency.",
    h1: "Injection Molding & Tooling for Home Appliances",
    heroCopy: "Mold design and plastic injection molding for appliance housings, control panels and structural components where appearance, fit, warpage control and repeatable production matter.",
    heroImage: "/images/industries/home-appliance.png", heroAlt: "Home appliances with molded housings controls panels and functional plastic components", secondaryCta: "Discuss an Appliance Project",
    applicationImage: "/images/industries/home-appliance-smart-home-components.webp", applicationAlt: "Home appliance housings panels controls and molded functional parts",
    applicationsHeading: "Molded Components for Home Appliance Products", applicationsIntro: "Programs cover visible outer housings and internal carriers, controls and air- or water-management features.",
    applications: [["Exterior Housings", "Large visible covers with controlled texture, gaps and assembly datums."], ["Control Panels & Bezels", "Interfaces around displays, buttons and touch-control assemblies."], ["Knobs & Buttons", "Repeated user-interface components requiring stable feel and finish."], ["Internal Frames", "Structural carriers for motors, PCBs, pumps and subassemblies."], ["Air & Water Components", "Ducts, reservoirs and flow features reviewed around geometry and resin."]],
    engineeringHeading: "Engineering Priorities for Appliance Plastic Parts", engineeringIntro: "Appliance parts often combine broad cosmetic surfaces, environmental exposure and multiple assembly interfaces.",
    engineeringConsiderations: [["Warpage & Flatness", "Control long surfaces through geometry, gating and cooling review."], ["Surface Appearance", "Coordinate texture, color, parting lines and gate vestige."], ["Heat & Moisture Exposure", "Confirm the customer-selected material grade against service conditions."], ["Assembly Datums", "Protect locating and fastening points across multipart housings."], ["Ribs & Structural Support", "Add stiffness without creating sink behind cosmetic walls."], ["Service & Reassembly", "Review clips, screws and access features around intended use."]],
    toolingHeading: "Tooling & Molding Considerations for Appliance Components", toolingIntro: "Tooling decisions balance broad-part filling, visible surfaces and reliable repeated assembly.",
    toolingConsiderations: [["Cooling balance", "Plan circuits around broad geometry to manage shrinkage."], ["Gate direction", "Review flow orientation and weld lines around openings and visible zones."], ["Texture release", "Confirm draft before applying specified texture."], ["Large-part ejection", "Distribute release forces to reduce whitening or deformation."], ["Cavity strategy", "Match cavitation to part size, volume and machine constraints."]],
    moldTypesIntro: "Home-appliance programs often require large, precision, hot-runner or multi-cavity tooling.", moldTypes: [mold.large, mold.precision, mold.hot, mold.multi],
    evidence: { eyebrow: "APPLICATION EVIDENCE", title: "Appliance Housing & Control Component Review", summary: "An application-specific view of housing, control and structural part families used during appliance tooling planning.", image: "/images/industries/home-appliance-smart-home-components.webp", alt: "Home appliance housings control panels and functional molded component examples", application: "Visible housings, control interfaces and internal structural components", engineeringFocus: "Warpage, surface appearance, assembly datums and repeat production", validation: "Sample appearance, critical dimensions and mating-part fit" },
    processIntro: "Appliance programs move through DFM, tool concept, design approval, trial and sample review before production release.",
    validationHeading: "Validation for Appliance Housings & Components", validationIntro: "Review criteria are agreed around visible quality, dimensional fit and final-appliance assembly conditions.",
    validationItems: [["Flatness & warpage", "Measure agreed housing conditions after defined cooling or conditioning."], ["Surface appearance", "Review texture, gloss, flow marks and visible witness lines."], ["Assembly fit", "Check covers, bezels, frames and fasteners with mating parts."], ["Functional interfaces", "Verify openings, mounts and moving controls against drawings."], ["Repeat samples", "Compare critical conditions across samples or cavities."]],
    resources: [resource.warpage, { title: "Wall Thickness Guidelines", body: "Manage transitions and local mass in large housings.", href: "/resources/injection-molding/wall-thickness-guidelines" }, resource.material], relatedCapabilities: caps("home appliance"),
    faqs: [["Which appliance parts can Arktech support?", "Scopes include housings, panels, bezels, knobs, controls, frames, ducts, reservoirs, bases and brackets."], ["How is warpage reviewed for large housings?", "DFM considers walls, ribs, gates, cooling and measurement conditions as one connected system."], ["Can texture and gloss requirements be included?", "Yes. Finish, draft, gate and parting-line requirements should be defined before mold release."], ["Can Arktech support assembly checks?", "Representative controls, fasteners and mating parts can be included when acceptance criteria are defined."]],
    ctaEyebrow: "HOME APPLIANCE RFQ", ctaHeading: "Discuss Your Home Appliance Application", ctaCopy: "Share CAD, material, visible-surface requirements, annual volume and mating-part information for review.",
    needsAssetReplacement: true, assetReplacementNote: "Replace with a verified Arktech appliance tooling or molded-part project image when publication approval is available."
  },
  {
    slug: "consumer-electronics", navTitle: "Consumer Electronics", eyebrow: "CONSUMER ELECTRONICS",
    seoTitle: "Consumer Electronics Injection Molding & Tooling | Arktech", metaDescription: "Custom tooling and plastic injection molding for electronic housings, bezels, buttons and structural components requiring appearance, precision and repeatable production.",
    h1: "Injection Molding & Tooling for Consumer Electronics", heroCopy: "Precision tooling and molded plastic parts for electronics enclosures, controls and structural components where appearance, compact assembly and production consistency are critical.",
    heroImage: "/images/industries/consumer-electronics-enclosures.png", heroAlt: "Consumer electronics with molded enclosures bezels controls and functional components", secondaryCta: "Discuss an Electronics Project",
    applicationImage: "/images/industries/consumer-electronics-enclosures.webp", applicationAlt: "Electronic housings bezels buttons and internal molded components",
    applicationsHeading: "Plastic Components for Consumer Electronics", applicationsIntro: "Support spans visible enclosures and smaller precision parts that locate electronics, controls and user interfaces.",
    applications: [["Device Enclosures", "Upper and lower housings with controlled gaps, ports and mounts."], ["Bezels & Display Frames", "Visible frames around screens, lenses and touch interfaces."], ["Buttons & Controls", "Tactile or two-material controls requiring consistent geometry."], ["Router & Hub Housings", "Ventilated enclosures for connected electronics."], ["Internal Carriers", "Structures locating PCBs, batteries, connectors and modules."]],
    engineeringHeading: "Engineering Priorities for Electronics Enclosures", engineeringIntro: "Compact products make every wall, boss, port and interface part of the assembly tolerance stack.",
    engineeringConsiderations: [["Thin-Wall Filling", "Review flow length, gates and restrictions before steel release."], ["Cosmetic Zones", "Define acceptable parting lines, ejector marks and gate vestige."], ["PCB & Battery Clearance", "Use real package data to protect internal space."], ["Insert Features", "Plan threaded or functional inserts around load and location."], ["Vent & Port Geometry", "Balance open area, steel strength and release."], ["Transparent Features", "Coordinate resin handling, polish, flow and protection."]],
    toolingHeading: "Tooling & Molding Considerations for Electronic Products", toolingIntro: "Tool construction focuses on appearance, compact features and repeatable enclosure assembly.",
    toolingConsiderations: [["Precision parting lines", "Place split lines around visible and closely fitted interfaces."], ["Fine shutoffs", "Review ports and vents for steel strength."], ["Multi-material controls", "Assess 2K or overmolding against the real material pair."], ["Polished surfaces", "Protect gloss and transparent zones through handling."], ["Cavity identification", "Maintain traceability where multiple cavities are used."]],
    moldTypesIntro: "Electronics programs can combine precision, 2K, overmolding and multi-cavity tooling.", moldTypes: [mold.precision, mold.twoK, mold.over, mold.multi],
    evidence: { eyebrow: "REAL TOOLING EVIDENCE", title: "Two-Shot Light-Cover Tooling", summary: "A real two-material tooling project demonstrating integrated clear and functional features for a visible electronic component.", image: "/images/case-studies/two-shot-light-cover.webp", alt: "Two-shot injection mold and molded light-cover components for an electronic product", application: "Visible light-cover component with integrated material interface", engineeringFocus: "Material interface, gate location, appearance and tooling sequence", validation: "Trial samples reviewed for interface quality, appearance and fit", href: "/case-studies/two-shot-2k-injection-mold-tooling", linkLabel: "View Two-Shot Tooling Project" },
    processIntro: "Electronics tooling progresses from package-aware DFM to sample approval with visible and functional interfaces checked together.",
    validationHeading: "Validation for Consumer Electronics Components", validationIntro: "Approval connects cosmetic criteria with PCB, connector, control and enclosure assembly requirements.",
    validationItems: [["Cosmetic inspection", "Review visible surfaces under agreed conditions."], ["Enclosure fit", "Check gaps, flushness, snaps and fasteners."], ["Electronic package check", "Confirm ports, mounts, battery space and connector access."], ["Transparent-part review", "Inspect flow features, gate vestige and clarity as required."], ["Cavity comparison", "Compare repeated parts by cavity where applicable."]],
    resources: [resource.transparent, resource.draft, resource.ribs], relatedCapabilities: caps("consumer electronics"),
    faqs: [["Which electronics components can Arktech support?", "Scopes include enclosures, bezels, controls, router housings, internal carriers and transparent features."], ["Can you support 2K or overmolded controls?", "Concepts can be reviewed against the real material pair, geometry and production requirements."], ["How are PCB interfaces validated?", "Representative hardware supports review of bosses, ports, clearances and datums."], ["Can clear components be molded?", "Transparent parts can be assessed around resin, polish, gate vestige, visual criteria and handling."]],
    ctaEyebrow: "CONSUMER ELECTRONICS RFQ", ctaHeading: "Discuss Your Consumer Electronics Application", ctaCopy: "Upload enclosure CAD, electronic-package data, material and finish requirements for review."
  },
  {
    slug: "pet-tech", navTitle: "Pet Tech Products", eyebrow: "PET TECH PRODUCTS",
    seoTitle: "Pet Tech Injection Molding & Product Tooling | Arktech", metaDescription: "Custom injection molds and molded plastic components for smart feeders, connected pet products, monitoring devices and automated pet-care products.",
    h1: "Injection Molding & Tooling for Pet Tech Products", heroCopy: "Tooling and molded plastic components for smart feeders, monitoring devices and automated pet-care products where consumer appearance and functional assembly must work together.",
    heroImage: "/images/industries/pet-lifestyle-product-parts.png", heroAlt: "Smart pet feeder water device camera and molded plastic product housings", secondaryCta: "Discuss a Pet Tech Project",
    applicationImage: "/images/industries/pet-lifestyle-product-parts.webp", applicationAlt: "Pet technology housings bowls camera enclosures and functional molded components",
    applicationsHeading: "Molded Components for Connected Pet Products", applicationsIntro: "Pet-tech programs combine consumer styling with moving, feeding, sensing or water-handling assemblies.",
    applications: [["Smart Feeders", "Housings, bowls, lids and dispensing parts around motors and sensors."], ["Water Devices", "Reservoir, cover and pump-related components with defined interfaces."], ["Pet Cameras", "Camera housings, bases and moving covers."], ["Smart Doors & Access", "Frames, latches and sensor housings for controlled access."], ["Automated Care Products", "Functional housings and carriers for motorized pet products."]],
    engineeringHeading: "Engineering Priorities for Pet Tech Products", engineeringIntro: "These products combine visible housings with moving mechanisms, removable cleaning parts and user-accessible assemblies.",
    engineeringConsiderations: [["Cleaning & Disassembly", "Plan removable components and fasteners around intended cleaning."], ["Motor & Sensor Packaging", "Protect alignment, clearance and service access."], ["Water-Handling Interfaces", "Define contact geometry without making unverified ingress claims."], ["Noise & Vibration Features", "Review mounting geometry around motors or pumps."], ["Consumer Appearance", "Control texture, color split, gates and witness lines."], ["Safe Edge Geometry", "Review exposed edges and openings against customer requirements."]],
    toolingHeading: "Tooling & Molding Considerations for Pet Tech Assemblies", toolingIntro: "Tool concepts account for multipart housings, removable components and functional geometry around mechanisms.",
    toolingConsiderations: [["Large housing fill", "Balance gate location, walls and cooling across styled enclosures."], ["Moving components", "Review clearances and datums for lids, doors and dispensers."], ["Side-action features", "Release ports, hooks and openings with serviceable actions."], ["Insert strategy", "Plan threads and metal features around use and assembly."], ["Assembly samples", "Validate representative subassemblies, not isolated parts only."]],
    moldTypesIntro: "Pet-tech products commonly use precision housing, complex-action, insert and large-component tooling.", moldTypes: [mold.precision, mold.complex, mold.insert, mold.large],
    evidence: { eyebrow: "APPLICATION EVIDENCE", title: "Smart Pet Product Component Review", summary: "An application-led view of housings, removable components and functional interfaces considered in pet-tech tooling.", image: "/images/industries/pet-lifestyle-product-parts.webp", alt: "Smart pet product housings feeder parts water-device components and camera enclosures", application: "Connected feeders, water devices and monitoring products", engineeringFocus: "Cleaning access, mechanism packaging, appearance and assembly", validation: "Mating-part fit, motion clearance, visible surfaces and critical dimensions" },
    processIntro: "Pet-tech projects move from assembly-aware DFM through tooling, functional samples and approved production conditions.",
    validationHeading: "Validation for Pet Tech Product Assemblies", validationIntro: "Validation reflects how molded parts interact with motors, sensors, removable components and the finished product.",
    validationItems: [["Assembly fit", "Review covers, bowls, reservoirs, frames and modules together."], ["Motion clearance", "Check doors, lids and dispensing mechanisms through travel."], ["Visible quality", "Inspect cosmetic zones, texture and witness marks."], ["Critical dimensions", "Record interfaces controlling fit or mechanism position."], ["Cleaning-related fit", "Confirm removable parts locate and reassemble as defined."]],
    resources: [resource.ribs, resource.material, { title: "Undercut Design", body: "Review hooks, latches and side features before choosing tooling actions.", href: "/resources/injection-molding/undercut-design" }], relatedCapabilities: caps("pet tech"),
    faqs: [["Which pet-tech products can Arktech support?", "Programs can include feeders, water devices, cameras, access products, trackers and automated-care housings."], ["Can moving mechanisms be checked during DFM?", "Yes. Motor, sensor and mating-part data supports clearance and mounting review."], ["Does Arktech claim pet food-contact certification?", "No. Any food-contact or compliance requirement must be defined and verified for the selected material and project."], ["Can the project include assembly validation?", "Representative assemblies can be checked when mating components and acceptance criteria are available."]],
    ctaEyebrow: "PET TECH RFQ", ctaHeading: "Discuss Your Pet Tech Application", ctaCopy: "Send product CAD, mechanism data, material targets, assembly needs and expected volume for review.",
    needsAssetReplacement: true, assetReplacementNote: "Replace with a verified Arktech pet-tech tooling or molded-part project image when publication approval is available."
  },
  {
    slug: "automotive", navTitle: "Automotive Components", eyebrow: "AUTOMOTIVE COMPONENTS",
    seoTitle: "Automotive Plastic Injection Molding & Tooling | Arktech", metaDescription: "Injection molds and plastic components for automotive interior controls, panels, vents and functional parts requiring dimensional consistency and controlled surface appearance.",
    h1: "Injection Molding & Tooling for Automotive Components", heroCopy: "Export tooling and molded plastic components for automotive interiors, controls and functional applications where texture, dimensional consistency and repeat production matter.",
    heroImage: "/images/industries/Automotive-Components.png", heroAlt: "Automotive interior dashboard controls vents and molded plastic components", secondaryCta: "Discuss an Automotive Project",
    applicationImage: "/images/industries/automotive-ev-components.webp", applicationAlt: "Automotive and EV charging housings connectors and functional molded components",
    applicationsHeading: "Automotive Interior & Functional Applications", applicationsIntro: "Arktech supports component tooling without implying vehicle-level approval or certification.",
    applications: [["Interior Controls", "Switch, button and control housings with visible and tactile requirements."], ["Vents & Airflow Parts", "Slats, frames and duct interfaces requiring controlled motion."], ["Panels & Bezels", "Appearance-critical frames, trims and control-panel parts."], ["Sensor Housings", "Compact enclosures with connector and mounting interfaces."], ["Connector Components", "Functional molded geometry around electrical and mechanical interfaces."]],
    engineeringHeading: "Engineering Priorities for Automotive Plastic Components", engineeringIntro: "Automotive components require project-specific control of visible surfaces, dimensional interfaces and repeated production.",
    engineeringConsiderations: [["Texture & Grain", "Coordinate draft, split lines and gates with visible finish."], ["Dimensional Stability", "Protect mounting, connector and moving interfaces."], ["Heat & Environment", "Confirm the exact material grade against service requirements."], ["Clip & Fastener Features", "Review stress, assembly direction and release."], ["Cavity Balance", "Plan repeat production around balanced filling and traceability."], ["Mating-Part Fit", "Use representative hardware to check gaps and motion."]],
    toolingHeading: "Tooling & Molding Considerations for Automotive Parts", toolingIntro: "Tooling is planned around supplied standards, destination machine, visible surfaces and validation scope.",
    toolingConsiderations: [["Texture-ready steel", "Complete appearance and draft review before texture release."], ["Precision actions", "Control sliders and shutoffs around clips and vents."], ["Balanced cavitation", "Validate filling and cooling across production cavities."], ["Material shrinkage", "Use the confirmed supplier grade for tool offsets."], ["Machine compatibility", "Align mold base and connections with destination equipment."]],
    moldTypesIntro: "Automotive programs frequently use multi-cavity, precision, complex-action and hot-runner tooling.", moldTypes: [mold.multi, mold.precision, mold.complex, mold.hot],
    evidence: { eyebrow: "REAL PROJECT EVIDENCE", title: "Automotive Sensor Housing Multi-Cavity Mold", summary: "A real tooling project for repeated sensor-housing components with cavity balance and dimensional consistency at the center of validation.", image: "/images/case-studies/automotive-multi-cavity-mold.webp", alt: "Automotive sensor housing multi-cavity injection mold and molded components", application: "Repeated automotive sensor-housing components", engineeringFocus: "Cavity balance, locating interfaces and dimensional stability", validation: "Cavity-specific samples and dimensional inspection", href: "/case-studies/automotive-sensor-housing-tooling", linkLabel: "View Automotive Tooling Project" },
    processIntro: "Automotive tooling progresses through requirements review, mold approval, cavity-aware trials and documented validation.",
    validationHeading: "Validation for Automotive Tooling & Molded Parts", validationIntro: "Inspection follows the drawing and customer requirements; no unverified PPAP or IATF claim is made.",
    validationItems: [["Cavity-specific inspection", "Keep measurements traceable to each cavity."], ["Texture & appearance", "Review visible zones and allowable molding marks."], ["Assembly interfaces", "Check clips, mounts, connectors and moving features."], ["Process parameters", "Record approved trial conditions."], ["Correction history", "Track actions and updated samples before release."]],
    resources: [resource.multi, resource.engineering, resource.warpage], relatedCapabilities: caps("automotive component"),
    faqs: [["Which automotive parts can Arktech support?", "Scopes include controls, vents, bezels, sensor housings, connector components and other functional parts."], ["Does Arktech claim IATF or PPAP capability?", "No unverified IATF certification or PPAP service is claimed. Documentation is agreed per project."], ["Can tooling be built for our molding plant?", "Yes. Destination machine and plant standards should be supplied before approval."], ["How is multi-cavity consistency reviewed?", "Samples and measurements can be identified by cavity for balance and dimensional review."]],
    ctaEyebrow: "AUTOMOTIVE COMPONENT RFQ", ctaHeading: "Discuss Your Automotive Component Application", ctaCopy: "Share CAD, material grade, texture requirements, annual volume and destination-machine standards."
  },
  {
    slug: "industrial-automation", navTitle: "Industrial Automation", eyebrow: "INDUSTRIAL AUTOMATION",
    seoTitle: "Industrial Automation Injection Molding & Tooling | Arktech", metaDescription: "Custom injection molds and plastic components for controllers, sensors, automation equipment housings and industrial products requiring functional geometry and production consistency.",
    h1: "Injection Molding & Tooling for Industrial Automation", heroCopy: "Engineering, export tooling and molded plastic components for controllers, sensors and automation equipment where functional geometry and stable production are priorities.",
    heroImage: "/images/industries/Industrial-parts.jpg", heroAlt: "Industrial automation housings sensors controllers and precision functional components", secondaryCta: "Discuss an Automation Project",
    applicationImage: "/images/industries/industrial-parts.webp", applicationAlt: "Industrial controller housings sensor enclosures and precision automation components",
    applicationsHeading: "Plastic Components for Industrial Automation", applicationsIntro: "Programs focus on functional housings and interfaces used around control, sensing, motion and factory equipment.",
    applications: [["Controller Housings", "Enclosures for controls, displays and industrial connections."], ["Sensor Enclosures", "Compact housings with cable and mounting interfaces."], ["Machine Interface Panels", "Bezels and panels around operator controls."], ["Automation Covers", "Protective covers for actuators and moving assemblies."], ["Industrial Fan Components", "Complex hub and blade geometry requiring coordinated release."]],
    engineeringHeading: "Engineering Priorities for Automation Components", engineeringIntro: "Industrial parts combine functional geometry, reinforced materials, inserts and repeated service access.",
    engineeringConsiderations: [["Functional Datums", "Control interfaces locating sensors, boards or hardware."], ["Insert & Thread Features", "Plan metal interfaces around torque and pull-out needs."], ["Cable Routing", "Protect bend, clearance and connector access."], ["Reinforced Materials", "Account for directional shrinkage and tool wear."], ["Complex Release", "Resolve ports and hooks with robust tooling actions."], ["Serviceability", "Review access around repeated maintenance."]],
    toolingHeading: "Tooling & Molding Considerations for Industrial Parts", toolingIntro: "Industrial tooling prioritizes durable mechanisms, replaceable wear areas and stable interfaces.",
    toolingConsiderations: [["Slider / lifter sequence", "Model the complete motion path for side features."], ["Wear & replaceability", "Design high-contact areas for practical maintenance."], ["Insert loading", "Define location and handling for metal features."], ["Cooling thick geometry", "Manage local mass in structural housings."], ["Dimensional conditioning", "Agree when material conditioning affects inspection."]],
    moldTypesIntro: "Automation parts can require complex-action, insert, precision and unscrewing molds.", moldTypes: [mold.complex, mold.insert, mold.precision, mold.unscrewing],
    evidence: { eyebrow: "REAL TOOLING EVIDENCE", title: "Industrial Fan-Blade Mold with Coordinated Sliders", summary: "A real complex injection mold showing coordinated side actions used to release detailed fan-blade geometry.", image: "/images/case-studies/fan-blade-mold.webp", alt: "Complex industrial fan-blade injection mold with coordinated slider mechanisms", application: "Industrial fan component with detailed hub and blade features", engineeringFocus: "Seven-direction slider concept, release sequence and serviceable actions", validation: "Dry-run movement, mold trial and molded-part review", href: "/injection-molds/complex-injection-molds", linkLabel: "Explore Complex Injection Molds" },
    processIntro: "Automation programs connect functional DFM with serviceable tooling, controlled trials and assembly-aware approval.",
    validationHeading: "Validation for Industrial Automation Components", validationIntro: "Validation centers on interfaces and mechanisms that determine fit, function and repeat production.",
    validationItems: [["Functional dimensions", "Inspect mounting, locating and movement-related features."], ["Insert position", "Verify metal-feature location and orientation."], ["Tool movement", "Confirm actions through dry run and molding trials."], ["Assembly fit", "Review electronics, sensors and hardware where available."], ["Repeatability", "Compare agreed conditions across samples and cavities."]],
    resources: [resource.slider, resource.engineering, { title: "Undercut Design", body: "Reduce avoidable tooling complexity while preserving function.", href: "/resources/injection-molding/undercut-design" }], relatedCapabilities: caps("industrial automation"),
    faqs: [["Which automation parts can Arktech support?", "Programs can include controller housings, sensor enclosures, panels, covers and functional parts."], ["Can tooling include sliders or unscrewing actions?", "Yes. The concept follows actual geometry, travel, steel, sequence and reliability requirements."], ["Can metal inserts be included?", "Insert molding or installed inserts can be reviewed against load, position and inspection requirements."], ["How are reinforced plastics handled?", "The exact grade is reviewed for drying, shrinkage, wear and conditioning."]],
    ctaEyebrow: "INDUSTRIAL AUTOMATION RFQ", ctaHeading: "Discuss Your Industrial Automation Application", ctaCopy: "Send CAD, material grade, hardware interfaces, volume and destination-machine requirements."
  },
  {
    slug: "medical-devices", navTitle: "Medical Device Components", eyebrow: "MEDICAL DEVICE COMPONENTS",
    seoTitle: "Medical Device Injection Molding & Tooling | Arktech", metaDescription: "Injection molds and molded plastic components for medical device housings, enclosures and functional parts with focus on dimensional control, material requirements and validation.",
    h1: "Injection Molding & Tooling for Medical Device Components", heroCopy: "Tooling and molded plastic components for medical and diagnostic equipment where dimensional control, material requirements and documented sample validation must be defined clearly.",
    heroImage: "/images/industries/medial-industry.webp", heroAlt: "Medical and diagnostic equipment with molded housings controls and functional components", secondaryCta: "Discuss a Medical Component",
    applicationImage: "/images/industries/medical-healthcare-device-parts.webp", applicationAlt: "Medical device housings transparent parts cartridges and diagnostic components",
    applicationsHeading: "Medical & Diagnostic Product Components", applicationsIntro: "Support covers moldable components without implying device approval, cleanroom production or medical-system certification.",
    applications: [["Diagnostic Housings", "Enclosures around screens, controls and electronics."], ["Equipment Covers & Panels", "Visible and structural covers used on equipment."], ["Cartridge Housings", "Controlled interfaces for replaceable modules."], ["Transparent Components", "Clear covers and windows with defined visual requirements."], ["Internal Carriers", "Structures locating boards, sensors or functional modules."]],
    engineeringHeading: "Engineering Priorities for Medical Device Components", engineeringIntro: "Review begins with customer-defined material, dimensional, appearance and validation requirements.",
    engineeringConsiderations: [["Critical Dimensions", "Identify interfaces controlling assembly or functional alignment."], ["Material Definition", "Work from the exact approved supplier grade."], ["Transparent Features", "Protect polish, gate and weld-line requirements."], ["Sealing Surfaces", "Review flatness and parting-line placement around defined seals."], ["Insert Interfaces", "Coordinate load, position and repeated assembly."], ["Traceable Inspection", "Agree dimensions, stages and report format before trials."]],
    toolingHeading: "Tooling & Molding Considerations for Medical Components", toolingIntro: "Tooling follows the supplied component specification and inspection plan; no regulatory or cleanroom claim is made.",
    toolingConsiderations: [["Precision steel conditions", "Protect critical interfaces with stable inserts and datums."], ["Part handling", "Plan ejection around visible or sensitive areas."], ["Material preparation", "Follow verified requirements for the selected grade."], ["Cavity traceability", "Maintain sample identity where multiple cavities are used."], ["Documented corrections", "Connect mold changes with updated samples and results."]],
    moldTypesIntro: "Medical components can require precision, multi-cavity, insert and transparent-part tooling.", moldTypes: [mold.precision, mold.multi, mold.insert, { title: "Transparent Part Tooling", body: "Polished tooling for clear covers and windows.", href: "/injection-molds/high-gloss-injection-molds" }],
    evidence: { eyebrow: "REAL APPLICATION EVIDENCE", title: "Medical Education Device Housing Project", summary: "A real product-development project showing the relationship between device housing geometry, internal interfaces and assembled-product requirements.", image: "/images/case-studies/medical-education-device.webp", alt: "Medical education device housing components engineering development and assembled product", application: "Medical education device enclosure and internal component set", engineeringFocus: "Housing interfaces, internal packaging and product assembly", validation: "Molded-component dimensions, visible surfaces and assembled-device fit" },
    processIntro: "Medical component programs move through requirements review, approved tooling data, controlled trials and documented validation.",
    validationHeading: "Documented Validation for Medical Components", validationIntro: "Inspection is based on customer drawings and agreed requirements; it does not imply regulatory approval of the finished device.",
    validationItems: [["Critical-dimension report", "Record nominal, tolerance and actual results."], ["Visual inspection", "Review defined cosmetic and transparent surfaces."], ["Assembly fit", "Check mating parts, inserts and fasteners where available."], ["Cavity traceability", "Identify sample results by cavity when applicable."], ["Trial documentation", "Retain parameters, observations and correction actions."]],
    resources: [resource.material, resource.transparent, resource.dfm], relatedCapabilities: caps("medical device component"),
    faqs: [["Which medical-related components can Arktech support?", "Typical scopes include housings, covers, panels, cartridges, transparent parts and internal carriers."], ["Does Arktech claim ISO 13485, cleanroom or FDA approval?", "No. This page makes no unverified ISO 13485, cleanroom or FDA claim."], ["Can dimensional reports be provided?", "Critical dimensions can be reported against customer drawings and an agreed scope."], ["Can transparent components be reviewed?", "Yes. Review covers exact resin, polish, flow path, handling and customer visual criteria."]],
    ctaEyebrow: "MEDICAL COMPONENT RFQ", ctaHeading: "Discuss Your Medical Device Component Application", ctaCopy: "Upload CAD, drawings, exact material requirements, critical dimensions and validation expectations."
  }
];

export const industryLandingPageBySlug = new Map(industryLandingPages.map((page) => [page.slug, page]));
